package com.waterx.safety.visitor;

import com.waterx.safety.auth.CurrentUser;import com.waterx.safety.common.BusinessException;import com.waterx.safety.site.SiteAccessService;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.springframework.http.HttpStatus;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.annotation.AuthenticationPrincipal;import org.springframework.web.bind.annotation.*;import java.time.OffsetDateTime;import java.util.*;

@RestController @RequestMapping("/api/v1")
public class VisitorController{private final JdbcClient jdbc;private final SiteAccessService sites;public VisitorController(JdbcClient j,SiteAccessService s){jdbc=j;sites=s;}
 @GetMapping("/public/visitor/{token}") Briefing publicBriefing(@PathVariable String token){return find(token);}
 @PostMapping("/public/visitor/{token}/register") Id register(@PathVariable String token,@Valid @RequestBody RegisterInput in){Briefing b=find(token);if(!in.acknowledged())throw new BusinessException("VISITOR_ACK_REQUIRED","请阅读并确认安全告知",HttpStatus.BAD_REQUEST);UUID id=UUID.randomUUID();jdbc.sql("insert into visitor_entry_record(id,tenant_id,site_id,briefing_id,visitor_name,mobile,company_name,visit_purpose,host_name,acknowledged) values(:id,:t,:s,:briefing,:name,:mobile,:company,:purpose,:host,true)").param("id",id).param("t",b.tenantId()).param("s",b.siteId()).param("briefing",b.id()).param("name",in.visitorName()).param("mobile",in.mobile()).param("company",in.companyName()).param("purpose",in.visitPurpose()).param("host",in.hostName()).update();return new Id(id);}
 @GetMapping("/safety/visitors/briefing") @PreAuthorize("hasAuthority('inspection:read')") Briefing adminBriefing(@AuthenticationPrincipal CurrentUser u,@RequestHeader("X-Site-Id")UUID s){sites.requireSiteAccess(u,s);return jdbc.sql("select access_token from visitor_safety_briefing where tenant_id=:t and site_id=:s").param("t",u.tenantId()).param("s",s).query(String.class).optional().map(this::find).orElseThrow(()->new BusinessException("BRIEFING_NOT_FOUND","访客安全告知尚未配置",HttpStatus.NOT_FOUND));}
 @GetMapping("/safety/visitors/records") @PreAuthorize("hasAuthority('inspection:read')") List<Record> records(@AuthenticationPrincipal CurrentUser u,@RequestHeader("X-Site-Id")UUID s){sites.requireSiteAccess(u,s);return jdbc.sql("select id,visitor_name,mobile,company_name,visit_purpose,host_name,registered_at,entry_status from visitor_entry_record where tenant_id=:t and site_id=:s order by registered_at desc").param("t",u.tenantId()).param("s",s).query((r,n)->new Record(r.getObject(1,UUID.class),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6),r.getObject(7,OffsetDateTime.class),r.getString(8))).list();}
 @PutMapping("/safety/visitors/briefing") @PreAuthorize("hasAuthority('inspection:manage')") void updateBriefing(@AuthenticationPrincipal CurrentUser u,@RequestHeader("X-Site-Id")UUID s,@Valid @RequestBody BriefingInput in){sites.requireSiteAccess(u,s);jdbc.sql("update visitor_safety_briefing set title=:title,briefing_content=:content,risk_map_description=:risk,evacuation_description=:evacuation,emergency_contact=:contact where tenant_id=:t and site_id=:s").param("title",in.title()).param("content",in.briefingContent()).param("risk",in.riskMapDescription()).param("evacuation",in.evacuationDescription()).param("contact",in.emergencyContact()).param("t",u.tenantId()).param("s",s).update();}
 private Briefing find(String token){return jdbc.sql("select b.id,b.tenant_id,b.site_id,s.name,b.access_token,b.title,b.briefing_content,b.risk_map_description,b.evacuation_description,b.emergency_contact,b.risk_map_url,b.evacuation_map_url from visitor_safety_briefing b join site s on s.tenant_id=b.tenant_id and s.id=b.site_id where b.access_token=:token and b.status='ACTIVE'").param("token",token).query((r,n)->new Briefing(r.getObject(1,UUID.class),r.getObject(2,UUID.class),r.getObject(3,UUID.class),r.getString(4),r.getString(5),r.getString(6),r.getString(7),r.getString(8),r.getString(9),r.getString(10),r.getString(11),r.getString(12))).optional().orElseThrow(()->new BusinessException("BRIEFING_NOT_FOUND","访客安全告知不存在或已停用",HttpStatus.NOT_FOUND));}
 public record Briefing(UUID id,UUID tenantId,UUID siteId,String siteName,String accessToken,String title,String briefingContent,String riskMapDescription,String evacuationDescription,String emergencyContact,String riskMapUrl,String evacuationMapUrl){}public record BriefingInput(@NotBlank String title,@NotBlank String briefingContent,String riskMapDescription,String evacuationDescription,String emergencyContact){}public record RegisterInput(@NotBlank String visitorName,String mobile,String companyName,@NotBlank String visitPurpose,@NotBlank String hostName,boolean acknowledged){}public record Record(UUID id,String visitorName,String mobile,String companyName,String visitPurpose,String hostName,OffsetDateTime registeredAt,String status){}public record Id(UUID id){}
}
