package com.waterx.safety.education;

import com.waterx.safety.auth.CurrentUser;import com.waterx.safety.common.BusinessException;import com.waterx.safety.site.SiteAccessService;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.springframework.beans.factory.annotation.Value;import org.springframework.http.*;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.annotation.AuthenticationPrincipal;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.MultipartFile;import java.io.*;import java.nio.file.*;import java.time.OffsetDateTime;import java.util.*;

@RestController @RequestMapping("/api/v1/safety/education")
public class SafetyEducationController{
 private static final long MAX=100L*1024*1024;private static final Set<String> TYPES=Set.of("application/pdf","application/vnd.ms-powerpoint","application/vnd.openxmlformats-officedocument.presentationml.presentation","video/mp4","video/webm","application/msword","application/vnd.openxmlformats-officedocument.wordprocessingml.document");
 private final JdbcClient jdbc;private final SiteAccessService sites;private final Path root;public SafetyEducationController(JdbcClient j,SiteAccessService s,@Value("${app.storage.local-dir}")String d){jdbc=j;sites=s;root=Path.of(d).toAbsolutePath().normalize();}
 @GetMapping("/courses/{courseId}/materials") @PreAuthorize("hasAuthority('employee:read')") List<Material> materials(@AuthenticationPrincipal CurrentUser u,@RequestHeader("X-Site-Id")UUID s,@PathVariable UUID courseId){sites.requireSiteAccess(u,s);return jdbc.sql("select id,original_name,content_type,file_size,uploaded_at from training_material where tenant_id=:t and course_id=:c and (site_id is null or site_id=:s) order by uploaded_at").param("t",u.tenantId()).param("c",courseId).param("s",s).query((r,n)->new Material(r.getObject(1,UUID.class),r.getString(2),r.getString(3),r.getLong(4),r.getObject(5,OffsetDateTime.class))).list();}
 @PostMapping(value="/courses/{courseId}/materials",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) @PreAuthorize("hasAuthority('employee:manage')") Material upload(@AuthenticationPrincipal CurrentUser u,@RequestHeader("X-Site-Id")UUID s,@PathVariable UUID courseId,@RequestPart("file")MultipartFile file){sites.requireSiteAccess(u,s);if(file.isEmpty()||file.getSize()>MAX)throw new BusinessException("MATERIAL_SIZE_INVALID","培训材料不能为空且不能超过100MB",HttpStatus.BAD_REQUEST);String type=file.getContentType()==null?"application/octet-stream":file.getContentType().toLowerCase();if(!TYPES.contains(type))throw new BusinessException("MATERIAL_TYPE_INVALID","仅支持PPT、视频、PDF和Word培训材料",HttpStatus.BAD_REQUEST);String original=Path.of(Objects.requireNonNullElse(file.getOriginalFilename(),"material")).getFileName().toString().replaceAll("[\\r\\n]","_");String ext=original.lastIndexOf('.')>=0?original.substring(original.lastIndexOf('.')):"";String key=u.tenantId()+"/"+s+"/training/"+courseId+"/"+UUID.randomUUID()+ext;Path target=root.resolve(key).normalize();if(!target.startsWith(root))throw new BusinessException("MATERIAL_PATH_INVALID","材料存储路径无效",HttpStatus.BAD_REQUEST);UUID id=UUID.randomUUID();try{Files.createDirectories(target.getParent());try(var input=file.getInputStream()){Files.copy(input,target,StandardCopyOption.REPLACE_EXISTING);}jdbc.sql("insert into training_material(id,tenant_id,site_id,course_id,original_name,storage_key,content_type,file_size,uploaded_by) values(:id,:t,:s,:course,:name,:key,:type,:size,:user)").param("id",id).param("t",u.tenantId()).param("s",s).param("course",courseId).param("name",original).param("key",key).param("type",type).param("size",file.getSize()).param("user",u.userId()).update();}catch(IOException e){throw new BusinessException("MATERIAL_SAVE_FAILED","培训材料保存失败",HttpStatus.INTERNAL_SERVER_ERROR);}return new Material(id,original,type,file.getSize(),OffsetDateTime.now());}
 @GetMapping("/commitments") @PreAuthorize("hasAuthority('employee:read')") List<Commitment> commitments(@AuthenticationPrincipal CurrentUser u,@RequestHeader("X-Site-Id")UUID s){sites.requireSiteAccess(u,s);return jdbc.sql("select a.id,t.name,t.version,t.position_scope,t.content,e.display_name,a.due_at,a.status,a.signed_at,a.signature_text from safety_commitment_assignment a join safety_commitment_template t on t.tenant_id=a.tenant_id and t.id=a.template_id join employee e on e.tenant_id=a.tenant_id and e.id=a.employee_id where a.tenant_id=:t and a.site_id=:s order by a.assigned_at desc").param("t",u.tenantId()).param("s",s).query((r,n)->new Commitment(r.getObject(1,UUID.class),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6),r.getObject(7,OffsetDateTime.class),r.getString(8),r.getObject(9,OffsetDateTime.class),r.getString(10))).list();}
 @GetMapping("/commitment-templates") @PreAuthorize("hasAuthority('employee:read')") List<CommitmentTemplate> templates(@AuthenticationPrincipal CurrentUser u,@RequestHeader("X-Site-Id")UUID s){sites.requireSiteAccess(u,s);return jdbc.sql("select id,code,name,position_scope,content,version,status from safety_commitment_template where tenant_id=:t and (site_id is null or site_id=:s) order by created_at desc").param("t",u.tenantId()).param("s",s).query((r,n)->new CommitmentTemplate(r.getObject(1,UUID.class),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6),r.getString(7))).list();}
 @PostMapping("/commitment-templates") @PreAuthorize("hasAuthority('employee:manage')") Id template(@AuthenticationPrincipal CurrentUser u,@RequestHeader("X-Site-Id")UUID s,@Valid @RequestBody TemplateInput in){sites.requireSiteAccess(u,s);UUID id=UUID.randomUUID();jdbc.sql("insert into safety_commitment_template(id,tenant_id,site_id,code,name,position_scope,content,version) values(:id,:t,:s,:code,:name,:scope,:content,:version)").param("id",id).param("t",u.tenantId()).param("s",s).param("code",in.code()).param("name",in.name()).param("scope",in.positionScope()).param("content",in.content()).param("version",in.version()).update();return new Id(id);}
 @PostMapping("/commitments") @PreAuthorize("hasAuthority('employee:manage')") Id assign(@AuthenticationPrincipal CurrentUser u,@RequestHeader("X-Site-Id")UUID s,@Valid @RequestBody AssignmentInput in){sites.requireSiteAccess(u,s);UUID id=UUID.randomUUID();jdbc.sql("insert into safety_commitment_assignment(id,tenant_id,site_id,template_id,employee_id,due_at) values(:id,:t,:s,:template,:employee,:due)").param("id",id).param("t",u.tenantId()).param("s",s).param("template",in.templateId()).param("employee",in.employeeId()).param("due",in.dueAt()).update();return new Id(id);}
 @PostMapping("/commitments/{id}/sign") @PreAuthorize("hasAuthority('employee:read')") void sign(@AuthenticationPrincipal CurrentUser u,@RequestHeader("X-Site-Id")UUID s,@PathVariable UUID id,@Valid @RequestBody SignInput in){sites.requireSiteAccess(u,s);int c=jdbc.sql("update safety_commitment_assignment set status='SIGNED',signed_at=now(),signer_user_id=:user,signature_text=:signature where tenant_id=:t and site_id=:s and id=:id and status='PENDING'").param("user",u.userId()).param("signature",in.signatureText()).param("t",u.tenantId()).param("s",s).param("id",id).update();if(c==0)throw new BusinessException("COMMITMENT_STATE_INVALID","承诺书不存在或已经签订",HttpStatus.CONFLICT);}
 public record Material(UUID id,String originalName,String contentType,long fileSize,OffsetDateTime uploadedAt){}public record Commitment(UUID id,String name,String version,String positionScope,String content,String employeeName,OffsetDateTime dueAt,String status,OffsetDateTime signedAt,String signatureText){}public record CommitmentTemplate(UUID id,String code,String name,String positionScope,String content,String version,String status){}public record TemplateInput(@NotBlank String code,@NotBlank String name,@NotBlank String positionScope,@NotBlank String content,@NotBlank String version){}public record AssignmentInput(@NotNull UUID templateId,@NotNull UUID employeeId,@NotNull OffsetDateTime dueAt){}public record SignInput(@NotBlank String signatureText){}public record Id(UUID id){}
}
