import type { HazardDetail, SafetyAttachment, WorkflowTask, WorkflowItem, WorkflowHazard } from '@safety/api-client'
export const hazardStatuses:Record<string,string>={PENDING_ACCEPTANCE:'待受理',ASSIGNED:'待接收',RECTIFYING:'整改中',REVIEW_PENDING:'待复查',CLOSED:'已归档',OPEN:'待受理',OVERDUE:'整改中（历史）'}
export const levels:Record<string,string>={GENERAL:'一般',SERIOUS:'严重',LARGER:'较大',MAJOR:'重大'}
export const legalStatuses:Record<string,string>={UNDETERMINED:'待核定',YES:'认定为重大',NO:'认定为非重大'}
export const resultNames:Record<string,string>={COMPLIANT:'符合',NON_COMPLIANT:'不符合',NOT_APPLICABLE:'不适用',RECORDED:'已记录'}
const stageNames:Record<string,string>={DISCOVERY:'发现',RECTIFICATION:'整改',REVIEW:'复查'}
export function inspectionAnswer(item:WorkflowItem){return ['CONDITION','OBSERVATION'].includes(item.questionType)?({YES:'是',NO:'否'} as Record<string,string>)[item.answer||'']||'未记录':item.answer??'未记录'}
export const eventNames:Record<string,string>={LEGACY_CAPTURE:'历史快照',REPORTED:'发现上报',INSPECTION_LINKED:'关联检查',ASSIGNED:'受理派发',RECEIVED:'责任人接收',ASSIGNMENT_RETURNED:'退回受理',RECTIFICATION_SUBMITTED:'提交整改',REVIEW_RETURNED:'复查退回',CLOSED:'复查归档',REMINDED:'站内催办',ATTACHMENT_ADDED:'追加附件'}
export function time(value?:string){return value?new Date(value).toLocaleString('zh-CN',{hour12:false}):'—'}
const escape=(value:unknown)=>String(value??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!))
export function download(content:string,name:string,type='text/html;charset=utf-8'){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}
export function csvContent(rows:unknown[][]){return '\ufeff'+rows.map(row=>row.map(v=>'"'+String(v??'').replace(/^(\s*)([=+@\-])/,"'$1$2").replace(/"/g,'""')+'"').join(',')).join('\r\n')}
export function csv(rows:unknown[][],name:string){download(csvContent(rows),name,'text/csv;charset=utf-8')}
function table(headers:string[],rows:unknown[][]){return '<table><thead><tr>'+headers.map(h=>'<th>'+escape(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(v=>'<td>'+escape(v)+'</td>').join('')+'</tr>').join('')+'</tbody></table>'}
function archiveDocument(title:string,body:string){return '<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>'+escape(title)+'</title><style>body{font:14px/1.7 sans-serif;margin:28px;color:#172d40}h1{font-size:24px}h2{font-size:17px;break-after:avoid}table{width:100%;border-collapse:collapse;margin:12px 0}th,td{border:1px solid #aaa;text-align:left;padding:8px;vertical-align:top;white-space:pre-wrap;overflow-wrap:anywhere}img{max-width:240px;max-height:90px}thead{display:table-header-group}tr{break-inside:avoid}.signature{break-inside:avoid}.event{margin-top:20px}.event h2{border-bottom:1px solid #aaa}.meta{font-size:12px}details pre{white-space:pre-wrap;overflow-wrap:anywhere}@media print{@page{size:A4 landscape;margin:12mm}body{margin:0;font-size:10pt;color:#000}button,details{display:none}th,td{padding:5px}h1{font-size:18pt}h2{font-size:12pt}}</style><body><h1>'+escape(title)+'</h1><button onclick="window.print()">打印记录</button>'+body+'</body></html>'}
function sign(value?:string){return value?.startsWith('data:image/png;base64,')?'<img alt="本人签署" src="'+escape(value)+'">':'<p>签署：未记录</p>'}
export function buildHazardArchive(d:HazardDetail,files:SafetyAttachment[]){const h=d.hazard;return archiveDocument('隐患整改记录 '+h.hazardNo,
 table(['字段','内容'],[['位置',h.location],['现象',h.description],['发现时间',time(h.discoveredAt)],['分类',h.categoryMajor],['内部等级',levels[h.hazardLevel]],['法定重大隐患认定',legalStatuses[h.legalMajorStatus]],['认定依据',h.legalMajorBasis],['整改措施',h.rectificationMeasure],['临时措施',h.temporaryMeasure],['责任部门／责任人',(h.responsibleOrg||'待明确')+' / '+(h.responsiblePerson||'待明确')],['期限',h.dueDate],['预计费用（元）',h.estimatedCost??'待确认'],['当前状态',hazardStatuses[h.status]],['版本',h.revision],['关联风险',h.riskName]])+
 '<h2>发现来源</h2>'+table(['检查任务','存在问题'],d.origins.map(o=>[o.taskNo,o.description]))+
 '<h2>当前整改与复查结论</h2>'+table(['完成情况','复查意见'],[[h.completionNote,h.reviewComment]])+
 '<p>下列逐次记录保留当时版本和签署；附件为索引，原文件应一并归档。历史缺失信息不以当前值补写。</p>'+
 d.events.map((e,index)=>{const s=e.snapshot;const signature=e.action==='RECTIFICATION_SUBMITTED'?s.rectification_signature:['REVIEW_RETURNED','CLOSED'].includes(e.action)?s.review_signature:undefined;
 const fields:unknown[][]=[['当时状态',hazardStatuses[String(s.status)]||s.status],['位置／现象',String(s.location??'未记录')+' / '+String(s.description??'未记录')],['当时责任人标识',s.responsible_employee_id],['当时责任部门标识',s.responsible_org_id],['期限',s.due_date],['内部等级',levels[String(s.hazard_level)]||s.hazard_level],['分类',s.category_major],['法定重大认定',legalStatuses[String(s.legal_major_status)]||'未记录'],['认定依据',s.legal_major_basis],['整改要求',s.rectification_measure],['临时措施',s.temporary_measure],['预计费用（元）',s.estimated_cost??'待确认'],['整改反馈',s.completion_note],['复查意见',s.review_comment]];
 return '<section class="event"><h2>'+escape(index+1)+'. '+escape(eventNames[e.action]||e.action)+' · V'+escape(e.revision)+'</h2><p class="meta">'+escape(time(e.occurredAt))+' · '+escape(e.actorName)+' · 事件标识：'+escape(e.id)+'</p><p>'+escape(e.note)+'</p>'+table(['当次留存字段','内容'],fields)+
 '<p>当时已关联的附件：'+escape(e.evidenceIds.map(id=>{const f=files.find(x=>x.id===id);return f?f.originalName+'（'+id+'）':id+'（原文件未取得）'}).join('；')||'无')+'</p>'+
 (['RECTIFICATION_SUBMITTED','REVIEW_RETURNED','CLOSED'].includes(e.action)?'<div class="signature"><p>'+escape(e.actorName)+' · '+escape(eventNames[e.action])+' · V'+escape(e.revision)+' · '+escape(time(e.occurredAt))+'</p>'+sign(typeof signature==='string'?signature:undefined)+'</div>':'')+
 '<details><summary>原始历史快照（留存，不参与打印）</summary><pre>'+escape(JSON.stringify({...s,rectification_signature:undefined,review_signature:undefined},null,2))+'</pre></details></section>'}).join('')+
 '<h2>附件索引</h2>'+table(['标识','阶段','文件','上传人','时间'],files.map(f=>[f.id,stageNames[f.stage],f.originalName,f.uploadedByName,time(f.uploadedAt)])))}
export function exportHazard(d:HazardDetail,files:SafetyAttachment[]){download(buildHazardArchive(d,files),d.hazard.hazardNo+'-整改记录.html')}
export function buildTaskArchive(t:WorkflowTask,items:WorkflowItem[]){return archiveDocument(t.title+' '+t.taskNo,
 table(['字段','内容'],[['模板',t.templateName+' V'+t.templateVersion],['快照来源',t.snapshotOrigin==='LEGACY_CAPTURE'?'升级时捕获的历史模板，非原始签署证明':'创建任务时冻结'],['实际部位',t.inspectionLocation],['组织及参加人员',t.participants],['执行人',t.assigneeName],['计划日期',t.plannedStart],['完成时间',time(t.completedAt)]])+
 table(['项目','检查内容与来源','原始回答','结论','不适用依据','存在问题／现场处置','关联隐患标识'],items.map(i=>[i.category,i.content+'\n'+(i.sourceRef||'来源未记录'),inspectionAnswer(i),resultNames[i.result||'']||'未记录',i.notApplicableReason,(i.problemDescription||'未记录')+'\n现场处置：'+(i.handlingMeasure||'未记录'),i.linkedHazardId]))+'<div class="signature"><p>检查人：'+escape(t.assigneeName)+' · 完成时间：'+escape(time(t.completedAt))+'</p>'+sign(t.signatureData)+'</div>')}
export function exportTask(t:WorkflowTask,items:WorkflowItem[]){download(buildTaskArchive(t,items),t.taskNo+'-检查记录.html')}
export function exportLedger(hazards:WorkflowHazard[]){csv([['隐患编号','位置','现象','发现时间','分类','旧分类','内部等级','法定重大认定','认定依据','整改措施','临时措施','责任部门','责任人','期限','预计费用（元）','状态','逾期天数','整改反馈','复查意见','关联风险'],...hazards.map(h=>[h.hazardNo,h.location,h.description,time(h.discoveredAt),h.categoryMajor,h.legacyCategoryMajor,levels[h.hazardLevel],legalStatuses[h.legalMajorStatus],h.legalMajorBasis,h.rectificationMeasure,h.temporaryMeasure,h.responsibleOrg,h.responsiblePerson,h.dueDate,h.estimatedCost,hazardStatuses[h.status],h.overdueDays,h.completionNote,h.reviewComment,h.riskName])],'隐患台账.csv')}
