<script setup lang="ts">
import { ref,computed,onMounted,watch,nextTick } from 'vue'
import type {ApiClient,SafetyContext,SafetyDirectory,WorkflowTask,WorkflowHazard,WorkflowTemplate,InspectionPlan,WorkflowItem,TemplateRevision} from '@safety/api-client'
import {WxButton,WxCard,WxTabs,WxTableSurface,WxDialog} from '../../components/waterx'
import SafetyWorkflowPanel from '@safety/workflow-ui'
import {hazardStatuses,levels,time,exportLedger,csv,resultNames,inspectionAnswer} from '@safety/workflow-ui/archive'
const props=defineProps<{api:ApiClient;siteId:string;page:'inspection'|'hazard'}>()
const emit=defineEmits<{updated:[]}>()
const api=props.api.forSite(props.siteId)
const context=ref<SafetyContext|null>(null),directory=ref<SafetyDirectory>({employees:[],units:[],risks:[]})
const tasks=ref<WorkflowTask[]>([]),hazards=ref<WorkflowHazard[]>([]),templates=ref<WorkflowTemplate[]>([]),plans=ref<InspectionPlan[]>([])
const tab=ref<'tasks'|'plans'|'templates'>('tasks'),search=ref(''),status=ref(''),mine=ref(false),month=ref(new Date().toISOString().slice(0,7))
const loading=ref(false),error=ref(''),message=ref(''),editorSurface=ref<HTMLFormElement|null>(null)
const panel=ref<'report'|'task'|'hazard'|null>(null),selectedTask=ref<WorkflowTask>(),hazardId=ref('')
const editor=ref<'task'|'plan'|'template'|'planStatus'|null>(null),selectedTemplate=ref<WorkflowTemplate>(),selectedPlan=ref<InspectionPlan>()
const templateItems=ref<WorkflowItem[]>([]),templateReason=ref(''),templateName=ref(''),planReason=ref(''),editorDirty=ref(false),confirmDiscard=ref(false)
const today=()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10)
const form=ref({templateId:'',name:'',plannedStart:today(),dueAt:today()+'T17:00',assigneeEmployeeId:'',scheduleType:'WEEKLY' as 'DAILY'|'WEEKLY'|'MONTHLY'|'ONCE',intervalValue:1,nextRunDate:today(),dueHours:24})
const taskNames:Record<string,string>={PENDING:'待执行',IN_PROGRESS:'执行中',OVERDUE:'已逾期',COMPLETED:'已完成',CANCELLED:'已取消'}
const scheduleNames:Record<string,string>={DAILY:'每日',WEEKLY:'每周',MONTHLY:'每月',ONCE:'一次性'}
const filteredTasks=computed(()=>tasks.value.filter(t=>(!status.value||t.status===status.value)&&(!mine.value||t.canExecute)&&(!search.value||[t.title,t.taskNo,t.assigneeName].join(' ').includes(search.value))))
const filteredHazards=computed(()=>hazards.value.filter(h=>(!status.value||h.status===status.value)&&(!mine.value||h.canReceive||h.canRectify||h.canReview||context.value?.canManage&&h.status==='PENDING_ACCEPTANCE')&&(!search.value||[h.hazardNo,h.description,h.location,h.responsiblePerson].join(' ').includes(search.value))))
const pending=computed(()=>hazards.value.filter(h=>h.status==='PENDING_ACCEPTANCE').length)
const overdue=computed(()=>hazards.value.filter(h=>h.overdueDays>0).length)
const employees=computed(()=>[...new Map(directory.value.employees.map(e=>[e.id,e])).values()])
watch(()=>props.page,()=>{status.value='';search.value='';mine.value=false})
async function refresh(){loading.value=true;error.value='';try{context.value=await api.safetyContext();[tasks.value,hazards.value,templates.value,plans.value]=await Promise.all([api.workflowTasks(),api.workflowHazards(),api.workflowTemplates(),api.inspectionPlans()]);if(context.value.canManage)directory.value=await api.safetyDirectory()}catch(e){error.value=(e as Error).message}finally{loading.value=false}}
onMounted(refresh)
function openTask(t:WorkflowTask){selectedTask.value=t;panel.value='task'}
function openHazard(h:WorkflowHazard){hazardId.value=h.id;panel.value='hazard'}
async function saved(id?:string){if(panel.value==='report'||panel.value==='task'){panel.value=null;message.value='记录已保存；待办和历史已更新'}await refresh();emit('updated')}
function create(kind:'task'|'plan'){form.value={templateId:templates.value.find(t=>t.familyCode.startsWith('SOURCE-'))?.id||'',name:'',plannedStart:today(),dueAt:today()+'T17:00',assigneeEmployeeId:'',scheduleType:'WEEKLY',intervalValue:1,nextRunDate:today(),dueHours:24};editor.value=kind;editorDirty.value=false;error.value=''}
async function viewTemplate(t:WorkflowTemplate){loading.value=true;error.value='';try{templateItems.value=await api.workflowTemplateItems(t.id);selectedTemplate.value=t;templateName.value=t.name;templateReason.value='';editor.value='template';editorDirty.value=false}catch(e){error.value=(e as Error).message}finally{loading.value=false}}
async function closeEditor(){if(loading.value)return;if(editorDirty.value){confirmDiscard.value=true;await nextTick();editorSurface.value?.scrollTo({top:0});return}editor.value=null}
async function saveEditor(){if(loading.value)return;loading.value=true;error.value='';try{
 if(editor.value==='task')await api.createInspectionTask({templateId:form.value.templateId,title:form.value.name,plannedStart:form.value.plannedStart,dueAt:new Date(form.value.dueAt).toISOString(),assigneeEmployeeId:form.value.assigneeEmployeeId})
 if(editor.value==='plan')await api.createInspectionPlan({templateId:form.value.templateId,name:form.value.name,scheduleType:form.value.scheduleType,intervalValue:form.value.intervalValue,nextRunDate:form.value.nextRunDate,dueHours:form.value.dueHours,assigneeEmployeeId:form.value.assigneeEmployeeId})
 if(editor.value==='planStatus'&&selectedPlan.value)await api.changeInspectionPlanStatus(selectedPlan.value.id,selectedPlan.value.status==='ACTIVE'?'PAUSE':'RESUME',planReason.value)
 if(editor.value==='template'&&selectedTemplate.value){const revision:TemplateRevision={version:selectedTemplate.value.version,name:templateName.value,reason:templateReason.value,items:templateItems.value.map(i=>({category:i.category,content:i.content,questionType:i.questionType,conditionIndex:i.conditionItemId?templateItems.value.findIndex(p=>p.id===i.conditionItemId):undefined,sourceRef:i.sourceRef}))};await api.reviseInspectionTemplate(selectedTemplate.value.id,revision)}
 editor.value=null;editorDirty.value=false;message.value='保存成功；历史任务保留原模板';await refresh();emit('updated')
 }catch(e){error.value=(e as Error).message}finally{loading.value=false}}
async function generate(){loading.value=true;try{const r=await api.generateInspectionPlans();message.value=`已生成${r.generatedCount}项到期任务`;await refresh();emit('updated')}catch(e){error.value=(e as Error).message}finally{loading.value=false}}
function planStatus(p:InspectionPlan){selectedPlan.value=p;planReason.value='';editor.value='planStatus';editorDirty.value=false}
function addItem(){templateItems.value.push({id:crypto.randomUUID(),category:'',content:'',required:true,sortOrder:templateItems.value.length+1,questionType:'COMPLIANCE'});editorDirty.value=true}
async function monthly(){loading.value=true;error.value='';try{const selected=tasks.value.filter(t=>t.plannedStart.startsWith(month.value));const rows:unknown[][]=[['计划日期','任务编号','任务','模板版本','执行人员','状态','完成时间','检查项目','检查内容','回答','结论','问题','临时处置','不适用理由']];for(const t of selected){const list=await api.workflowTaskItems(t.id);for(const i of list)rows.push([t.plannedStart,t.taskNo,t.title,t.templateVersion,t.assigneeName,taskNames[t.status],time(t.completedAt),i.category,i.content,inspectionAnswer(i),resultNames[i.result||'']||'未记录',i.problemDescription,i.handlingMeasure,i.notApplicableReason])}csv(rows,`${month.value}-检查月度记录.csv`);message.value=`已导出${selected.length}项任务；未完成项不会当作已检查`}catch(e){error.value=(e as Error).message}finally{loading.value=false}}
</script>
<template>
<section class="safety-workspace">
 <p v-if="error&&!editor" class="safety-error" role="alert">{{error}}</p><p v-if="message" class="safety-message" role="status">{{message}}</p>
 <div class="safety-toolbar"><label><input v-model="search" placeholder="搜索编号、问题或责任人" aria-label="搜索安全记录"/></label><label><input v-model="mine" type="checkbox"/>我的待办</label><WxButton :loading="loading" @click="refresh">刷新</WxButton><WxButton v-if="page==='hazard'&&context&&context.canReport!==false" variant="primary" @click="panel='report'">现场问题上报</WxButton><WxButton v-if="page==='hazard'" @click="exportLedger(filteredHazards)">导出台账</WxButton></div>
 <p v-if="context" class="safety-scope">{{context.displayName}} · {{context.canManage?'可受理、派发和复查；不能验收本人整改':context.canReport===false?'管理层只读；不代行上报、整改或复查':'本人执行、上报和整改；专业步骤由安全管理人员处理'}}</p>
 <template v-if="page==='inspection'">
  <WxTabs class="safety-tabs" aria-label="安全检查视图"><button v-for="t in (['tasks','plans','templates'] as const)" :key="t" :class="{active:tab===t}" @click="tab=t">{{({tasks:'检查任务',plans:'检查计划',templates:'模板库'})[t]}}</button></WxTabs>
  <template v-if="tab==='tasks'"><div class="safety-toolbar"><select v-model="status" aria-label="检查状态"><option value="">全部状态</option><option v-for="(label,key) in taskNames" :key="key" :value="key">{{label}}</option></select><label>汇总月份<input v-model="month" type="month"/></label><WxButton :disabled="loading" @click="monthly">导出月度记录</WxButton><WxButton v-if="context?.canManage" variant="primary" @click="create('task')">创建检查任务</WxButton></div>
   <WxTableSurface><div class="safety-table-scroll"><table><thead><tr><th>任务与模板</th><th>执行人</th><th>计划／截止</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="t in filteredTasks" :key="t.id"><td><b>{{t.title}}</b><small>{{t.taskNo}}</small><small>{{t.templateName}} · V{{t.templateVersion}}</small></td><td>{{t.assigneeName||'未指派'}}</td><td>{{t.plannedStart}}<small>{{time(t.dueAt)}}</small></td><td>{{taskNames[t.status]}}<small v-if="t.status==='COMPLETED'">关联问题{{t.hazardCount}}项</small></td><td><WxButton @click="openTask(t)">{{t.canExecute?'执行检查':'查看记录'}}</WxButton></td></tr><tr v-if="!filteredTasks.length"><td colspan="5">{{loading?'正在读取…':error?'读取失败，请刷新重试':'暂无符合条件的任务'}}</td></tr></tbody></table></div></WxTableSurface>
  </template>
  <template v-else-if="tab==='plans'"><div class="safety-toolbar"><span>周期计划自动生成待办；恢复后从当天续排，不补记暂停期为已检查。</span><WxButton v-if="context?.canManage" :loading="loading" @click="generate">生成到期待办</WxButton><WxButton v-if="context?.canManage" variant="primary" @click="create('plan')">新建计划</WxButton></div><WxTableSurface><div class="safety-table-scroll"><table><thead><tr><th>计划</th><th>模板</th><th>频次与下一次</th><th>执行人</th><th>状态与操作</th></tr></thead><tbody><tr v-for="p in plans" :key="p.id"><td>{{p.name}}<small>{{p.code}}</small></td><td>{{p.templateName}}</td><td>{{scheduleNames[p.scheduleType]}} · 每{{p.intervalValue}}周期<small>{{p.nextRunDate}} · {{p.dueHours}}小时内完成</small></td><td>{{p.assigneeName||'未指派'}}</td><td>{{({ACTIVE:'启用',PAUSED:'暂停',COMPLETED:'已完成'} as Record<string,string>)[p.status]}}<WxButton v-if="context?.canManage&&p.status!=='COMPLETED'" @click="planStatus(p)">{{p.status==='ACTIVE'?'暂停':'恢复'}}</WxButton></td></tr></tbody></table></div></WxTableSurface></template>
  <template v-else><p class="safety-scope">9类原表模板与历史示例分别标示。发布修订只影响本厂后续任务；已生成任务保留原版本。</p><div class="safety-templates"><WxCard v-for="t in templates" :key="t.id"><h3>{{t.name}} <small>V{{t.version}}</small></h3><p>{{t.frequency}} · {{t.itemCount}}项</p><p>{{t.sourceName}}</p><WxButton @click="viewTemplate(t)">{{context?.canManage?'查看／修订模板':'查看模板'}}</WxButton></WxCard></div></template>
 </template>
 <template v-else><div v-if="!error&&!loading" class="safety-summary"><span>待受理 <b>{{pending}}</b></span><span>待复查 <b>{{hazards.filter(h=>h.status==='REVIEW_PENDING').length}}</b></span><span>逾期 <b>{{overdue}}</b></span></div><div class="safety-toolbar"><select v-model="status" aria-label="隐患状态"><option value="">全部状态</option><option v-for="(label,key) in hazardStatuses" :key="key" :value="key">{{label}}</option></select><span>内部等级与法定重大认定分别记录；空值表示待确认。</span></div><WxTableSurface><div class="safety-table-scroll"><table><thead><tr><th>编号／现场问题</th><th>分类／内部等级</th><th>责任与期限</th><th>当前状态</th><th>操作</th></tr></thead><tbody><tr v-for="h in filteredHazards" :key="h.id"><td><small>{{h.hazardNo}}</small><b>{{h.location}}</b><p>{{h.description}}</p></td><td>{{h.categoryMajor||'待专业确认'}}<small>{{levels[h.hazardLevel]||'待定级'}}</small></td><td>{{h.responsiblePerson||'待派发'}}<small>{{h.responsibleOrg||'待明确'}}</small><small>{{h.dueDate||'期限待确认'}}</small></td><td>{{hazardStatuses[h.status]}}<small v-if="h.overdueDays" class="safety-danger">逾期{{h.overdueDays}}天</small><small v-if="h.reminderCount">站内催办{{h.reminderCount}}次</small></td><td><WxButton @click="openHazard(h)">{{h.canAssign?'受理／详情':h.canReceive?'接收责任':h.canRectify?'反馈整改':h.canReview?'复查／详情':'查看记录'}}</WxButton></td></tr><tr v-if="!filteredHazards.length"><td colspan="5">{{loading?'正在读取…':error?'读取失败，请刷新重试':'暂无符合条件的记录'}}</td></tr></tbody></table></div></WxTableSurface></template>
 <WxDialog :open="!!panel" label="安全记录详情" placement="right" :close-on-backdrop="false" :close-on-escape="false"><SafetyWorkflowPanel v-if="panel&&context" :key="panel+(panel==='task'?selectedTask?.id:panel==='report'?'new':hazardId)" :api="api" :context="context" :mode="panel" :task="selectedTask" :hazard-id="hazardId" :hazards="hazards" :directory="directory" :draft-key="`safety:${context.userId}:${siteId}:${panel}:${panel==='task'?selectedTask?.id:panel==='report'?'new':hazardId}`" @close="panel=null" @saved="saved"/></WxDialog>
 <WxDialog :open="!!editor" label="检查配置" :close-on-backdrop="false" :close-on-escape="false"><form ref="editorSurface" class="safety-editor" @submit.prevent="saveEditor" @input="editorDirty=true"><header><h2>{{editor==='template'?'检查模板与修订':editor==='planStatus'?'调整计划状态':editor==='plan'?'新建检查计划':'创建检查任务'}}</h2><WxButton @click="closeEditor">关闭</WxButton></header><p v-if="error" class="safety-error" role="alert">{{error}}</p><div v-if="confirmDiscard" role="alert"><p>未保存内容将被放弃。</p><WxButton @click="editor=null;confirmDiscard=false;editorDirty=false">放弃并关闭</WxButton><WxButton @click="confirmDiscard=false">继续编辑</WxButton></div>
  <template v-if="editor==='task'||editor==='plan'"><label>检查模板<select v-model="form.templateId" required><option value="">请选择</option><option v-for="t in templates" :key="t.id" :value="t.id">{{t.name}} V{{t.version}} · {{t.sourceName}}</option></select></label><label>{{editor==='task'?'任务名称':'计划名称'}}<input v-model="form.name" required maxlength="200"/></label><label>执行人<select v-model="form.assigneeEmployeeId" required><option value="">请选择本人执行的责任人</option><option v-for="e in employees" :key="e.id" :value="e.id">{{e.displayName}} · {{e.organization}}</option></select></label><template v-if="editor==='task'"><label>计划日期<input v-model="form.plannedStart" type="date" required/></label><label>截止时间<input v-model="form.dueAt" type="datetime-local" required/></label></template><template v-else><label>周期<select v-model="form.scheduleType"><option v-for="(label,key) in scheduleNames" :key="key" :value="key">{{label}}</option></select></label><label>周期间隔<input v-model.number="form.intervalValue" type="number" min="1" max="365" required/></label><label>首次生成日期<input v-model="form.nextRunDate" type="date" required/></label><label>完成时限（小时）<input v-model.number="form.dueHours" type="number" min="1" max="8760" required/></label></template></template>
  <template v-else-if="editor==='planStatus'"><p>{{selectedPlan?.name}} · {{selectedPlan?.status==='ACTIVE'?'暂停期间不生成新任务':'恢复从当天续排，历史未执行任务仍保留'}}</p><label>调整原因<textarea v-model="planReason" required/></label></template>
  <template v-else-if="editor==='template'"><p>{{selectedTemplate?.sourceName}}</p><p>{{selectedTemplate?.instructions}}</p><label>模板名称<input v-model="templateName" required :disabled="!context?.canManage"/></label><div v-for="(item,index) in templateItems" :key="item.id" class="safety-template-item"><label>第{{index+1}}项分类<input v-model="item.category" required :disabled="!context?.canManage"/></label><label>检查内容<textarea v-model="item.content" required :disabled="!context?.canManage"/></label><label>题型<select v-model="item.questionType" :disabled="!context?.canManage"><option value="COMPLIANCE">合规结论</option><option value="CONDITION">场景条件</option><option value="OBSERVATION">是否发现问题（是→问题）</option><option value="TEXT">自由记录</option><option value="NUMBER">数值记录（不自动判合格）</option></select></label><label>前置条件<select v-model="item.conditionItemId" :disabled="!context?.canManage"><option :value="undefined">无</option><option v-for="(p,n) in templateItems.slice(0,index).filter(i=>i.questionType==='CONDITION')" :key="p.id" :value="p.id">{{p.content}}</option></select></label><small>{{item.sourceRef||'本厂补充'}}</small><WxButton v-if="context?.canManage" @click="templateItems.splice(index,1);editorDirty=true">移除此草稿项</WxButton></div><WxButton v-if="context?.canManage" @click="addItem()">补充检查项</WxButton><label v-if="context?.canManage">本次修订原因及项目适用说明<textarea v-model="templateReason" required/></label></template>
  <footer v-if="context?.canManage"><span>{{editor==='template'?'保存为本厂新版本，历史任务保持不变':''}}</span><WxButton type="submit" variant="primary" :loading="loading">{{editor==='template'?'发布本厂修订':'保存'}}</WxButton></footer>
 </form></WxDialog>
</section>
</template>
<style scoped>
.safety-workspace{display:grid;gap:14px;min-width:0}.safety-toolbar{display:flex;align-items:center;gap:10px;flex-wrap:wrap;font-size:13px}.safety-toolbar label{display:flex;align-items:center;gap:6px}.safety-toolbar input:not([type=checkbox]),.safety-toolbar select{height:34px;border:1px solid var(--wx-n200,#d4e0e6);border-radius:4px;padding:5px 9px;background:#fff;color:inherit}.safety-toolbar input[type=checkbox]{width:16px;height:16px}.safety-scope{font-size:13px;color:var(--wx-muted,#607b89);margin:0}.safety-summary{display:flex;gap:28px;padding:10px 0}.safety-summary b{font-size:20px;margin-left:8px}.safety-table-scroll{max-height:calc(100vh - 330px);min-height:180px;overflow:auto;scrollbar-width:thin}.safety-workspace table{width:100%;min-width:780px;border-collapse:collapse;table-layout:fixed;font-size:13px}.safety-workspace th,.safety-workspace td{padding:12px 10px;border-bottom:1px solid var(--wx-n200,#d4e0e6);text-align:left;vertical-align:top;overflow-wrap:anywhere}.safety-workspace th{position:sticky;top:0;background:#f5f8fa;border-top:1px solid var(--wx-n200,#d4e0e6);z-index:1}.safety-workspace th:first-child{width:32%}.safety-workspace th:last-child{width:135px}.safety-workspace td small{display:block;margin-top:5px;color:var(--wx-muted,#607b89)}.safety-workspace td p{margin:4px 0}.safety-templates{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:14px}.safety-templates h3{font-size:15px}.safety-templates p{font-size:13px;color:#647787}.safety-error{color:var(--wx-danger,#b42318);background:#fff3f1;padding:12px}.safety-message{color:#245978;background:#eef5fa;padding:10px}.safety-workspace .safety-danger{color:var(--wx-danger,#b42318)}.safety-editor{padding:24px;display:grid;gap:14px;min-width:0}.safety-editor header,.safety-editor footer{display:flex;justify-content:space-between;align-items:center;gap:14px}.safety-editor h2{font-size:20px;margin:0}.safety-editor label{display:grid;gap:6px;font-size:13px}.safety-editor input,.safety-editor select,.safety-editor textarea{font:inherit;padding:8px;border:1px solid #dbe4eb;border-radius:4px;width:100%;min-height:36px}.safety-editor textarea{min-height:70px;resize:vertical}.safety-template-item{display:grid;gap:10px;border-top:1px solid #dbe4eb;padding-top:16px}.safety-template-item small{color:#647787}.safety-editor :focus-visible{outline:2px solid #438bb2;outline-offset:2px}
.safety-workspace .safety-tabs{display:flex;flex-direction:row;gap:4px;margin:0 0 16px;padding:0;border-bottom:1px solid var(--wx-n200);overflow-x:auto}.safety-tabs button{width:auto;min-width:96px;display:block;border:0;border-radius:4px 4px 0 0;padding:10px 16px;background:transparent;color:var(--wx-muted);box-shadow:none;white-space:nowrap}.safety-tabs button:hover,.safety-tabs button.active{color:var(--wx-accent);background:var(--wx-n0);box-shadow:none}.safety-templates :deep(.wx-card){padding:16px}
.safety-tabs button.active{border-radius:8px 8px 0 0;background:var(--wx-n25);box-shadow:inset 0 3px var(--wx-blue-500)}
.safety-workspace th,.safety-workspace td{border-bottom:var(--wx-border-subtle)}.safety-workspace th{border-top:var(--wx-border-subtle);color:var(--wx-n500);background:var(--wx-n25)}
.safety-editor input,.safety-editor select,.safety-editor textarea{color:var(--wx-n700);background:var(--wx-n0);border:var(--wx-border-default)}.safety-editor :disabled{color:var(--wx-n500);background:var(--wx-n50)}
.safety-editor header{position:sticky;top:-24px;background:var(--wx-n0);z-index:2;padding:12px 0;border-bottom:var(--wx-border-subtle)}
.safety-editor{width:min(680px,calc(100vw - 32px));max-height:calc(100dvh - 32px);overflow:auto;background:var(--wx-n0);border:var(--wx-border-default);border-radius:8px;box-sizing:border-box;scrollbar-width:thin}
</style>
