package com.waterx.safety.health;

import com.waterx.safety.auth.CurrentUser;import com.waterx.safety.site.SiteAccessService;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.annotation.AuthenticationPrincipal;import org.springframework.web.bind.annotation.*;import java.time.LocalDate;import java.util.*;

@RestController @RequestMapping("/api/v1/safety/occupational-health")
public class OccupationalHealthController{
 private final JdbcClient jdbc;private final SiteAccessService sites;public OccupationalHealthController(JdbcClient j,SiteAccessService s){jdbc=j;sites=s;}
 @GetMapping("/summary") @PreAuthorize("hasAuthority('employee:read')") Summary summary(@AuthenticationPrincipal CurrentUser u,@RequestHeader("X-Site-Id")UUID s){sites.requireSiteAccess(u,s);return jdbc.sql("select (select count(*) from occupational_hazard_factor where tenant_id=:t and site_id=:s and status='ACTIVE'),(select count(*) from occupational_hazard_factor where tenant_id=:t and site_id=:s and next_monitoring_on<=current_date+30),(select count(*) from occupational_health_exam where tenant_id=:t and site_id=:s),(select count(*) from occupational_health_exam where tenant_id=:t and site_id=:s and next_exam_on<=current_date+45)").param("t",u.tenantId()).param("s",s).query((r,n)->new Summary(r.getInt(1),r.getInt(2),r.getInt(3),r.getInt(4))).single();}
 @GetMapping("/factors") @PreAuthorize("hasAuthority('employee:read')") List<Factor> factors(@AuthenticationPrincipal CurrentUser u,@RequestHeader("X-Site-Id")UUID s){sites.requireSiteAccess(u,s);return jdbc.sql("select id,factor_name,factor_type,location,exposed_positions,exposure_level,limit_value,control_measures,monitoring_frequency,last_monitored_on,next_monitoring_on,case when next_monitoring_on<current_date then 'OVERDUE' when next_monitoring_on<=current_date+30 then 'DUE_SOON' else 'NORMAL' end from occupational_hazard_factor where tenant_id=:t and site_id=:s order by next_monitoring_on").param("t",u.tenantId()).param("s",s).query((r,n)->new Factor(r.getObject(1,UUID.class),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6),r.getString(7),r.getString(8),r.getString(9),r.getObject(10,LocalDate.class),r.getObject(11,LocalDate.class),r.getString(12))).list();}
 @GetMapping("/exams") @PreAuthorize("hasAuthority('employee:read')") List<Exam> exams(@AuthenticationPrincipal CurrentUser u,@RequestHeader("X-Site-Id")UUID s){sites.requireSiteAccess(u,s);return jdbc.sql("select x.id,e.display_name,x.exam_type,x.exam_date,x.medical_institution,x.conclusion,x.restricted_items,x.follow_up_action,x.next_exam_on from occupational_health_exam x join employee e on e.tenant_id=x.tenant_id and e.id=x.employee_id where x.tenant_id=:t and x.site_id=:s order by x.exam_date desc").param("t",u.tenantId()).param("s",s).query((r,n)->new Exam(r.getObject(1,UUID.class),r.getString(2),r.getString(3),r.getObject(4,LocalDate.class),r.getString(5),r.getString(6),r.getString(7),r.getString(8),r.getObject(9,LocalDate.class))).list();}
 @PostMapping("/factors") @PreAuthorize("hasAuthority('employee:manage')") Id factor(@AuthenticationPrincipal CurrentUser u,@RequestHeader("X-Site-Id")UUID s,@Valid @RequestBody FactorInput in){sites.requireSiteAccess(u,s);UUID id=UUID.randomUUID();jdbc.sql("insert into occupational_hazard_factor(id,tenant_id,site_id,factor_name,factor_type,location,exposed_positions,exposure_level,limit_value,control_measures,monitoring_frequency,last_monitored_on,next_monitoring_on) values(:id,:t,:s,:name,:type,:location,:positions,:level,:limit,:measures,:frequency,:last,:next)").param("id",id).param("t",u.tenantId()).param("s",s).param("name",in.factorName()).param("type",in.factorType()).param("location",in.location()).param("positions",in.exposedPositions()).param("level",in.exposureLevel()).param("limit",in.limitValue()).param("measures",in.controlMeasures()).param("frequency",in.monitoringFrequency()).param("last",in.lastMonitoredOn()).param("next",in.nextMonitoringOn()).update();return new Id(id);}
 @PostMapping("/factors/{id}/monitoring") @PreAuthorize("hasAuthority('employee:manage')") void monitoring(@AuthenticationPrincipal CurrentUser u,@RequestHeader("X-Site-Id")UUID s,@PathVariable UUID id,@Valid @RequestBody MonitoringInput in){sites.requireSiteAccess(u,s);jdbc.sql("update occupational_hazard_factor set exposure_level=:result,last_monitored_on=:date,next_monitoring_on=:next where tenant_id=:t and site_id=:s and id=:id").param("result",in.result()).param("date",in.monitoredOn()).param("next",in.nextMonitoringOn()).param("t",u.tenantId()).param("s",s).param("id",id).update();}
 @PostMapping("/exams") @PreAuthorize("hasAuthority('employee:manage')") Id exam(@AuthenticationPrincipal CurrentUser u,@RequestHeader("X-Site-Id")UUID s,@Valid @RequestBody ExamInput in){sites.requireSiteAccess(u,s);UUID id=UUID.randomUUID();jdbc.sql("insert into occupational_health_exam(id,tenant_id,site_id,employee_id,exam_type,exam_date,medical_institution,conclusion,restricted_items,follow_up_action,next_exam_on) values(:id,:t,:s,:employee,:type,:date,:institution,:conclusion,:restricted,:action,:next)").param("id",id).param("t",u.tenantId()).param("s",s).param("employee",in.employeeId()).param("type",in.examType()).param("date",in.examDate()).param("institution",in.medicalInstitution()).param("conclusion",in.conclusion()).param("restricted",in.restrictedItems()).param("action",in.followUpAction()).param("next",in.nextExamOn()).update();return new Id(id);}
 public record Summary(int activeFactors,int monitoringDue,int examRecords,int examDue){}public record Factor(UUID id,String factorName,String factorType,String location,String exposedPositions,String exposureLevel,String limitValue,String controlMeasures,String monitoringFrequency,LocalDate lastMonitoredOn,LocalDate nextMonitoringOn,String dueStatus){}public record Exam(UUID id,String employeeName,String examType,LocalDate examDate,String medicalInstitution,String conclusion,String restrictedItems,String followUpAction,LocalDate nextExamOn){}public record FactorInput(@NotBlank String factorName,@NotBlank String factorType,@NotBlank String location,@NotBlank String exposedPositions,String exposureLevel,String limitValue,@NotBlank String controlMeasures,@NotBlank String monitoringFrequency,LocalDate lastMonitoredOn,LocalDate nextMonitoringOn){}public record MonitoringInput(@NotNull LocalDate monitoredOn,@NotBlank String result,@NotNull LocalDate nextMonitoringOn){}public record ExamInput(@NotNull UUID employeeId,@NotBlank String examType,@NotNull LocalDate examDate,@NotBlank String medicalInstitution,@NotBlank String conclusion,String restrictedItems,String followUpAction,LocalDate nextExamOn){}public record Id(UUID id){}
}
