import type { LabFieldDefinition, LabTemplate, LabTemplateCode } from './types'

const f = (key:string,label:string,symbol:string,unit:string,group:LabFieldDefinition['group'],defaultValue:string,extra:Partial<LabFieldDefinition>={}):LabFieldDefinition => ({
  key,label,symbol,unit,group,defaultValue,required:true,inputType:'number',step:'any',...extra,
})

const sample = [
  f('sampleVolume','取样体积','V','mL','样品与环境','100'),
  f('dilution','稀释倍数','n','—','样品与环境','1'),
]
const curve = [
  f('blankAbsorbance','空白吸光度','A₀','Abs','标准与试剂','0.020'),
  f('curveSlope','标准曲线斜率','a','Abs/μg','标准与试剂','0.00653'),
  f('curveIntercept','标准曲线截距','b','Abs','标准与试剂','0.00317'),
]
const spectroResults = [{key:'mass',label:'曲线换算质量',unit:'μg',decimals:4},{key:'concentration',label:'检测结果',unit:'mg/L',decimals:3}]

export const labTemplates:LabTemplate[] = [
  {code:'Y01',title:'pH值检测记录（污水/污泥）',shortName:'pH',category:'水质检测',ledgerNo:'CQSWHY2026-Y01',method:'电极法 · HJ 1147—2020',methodVersion:'HJ 1147—2020',methodState:'现行方法',formulaVersion:'FX-Y01-V0.1',formulaText:'pH = 两次稳定示值的算术平均值',frequency:'日检',existing:false,
    fields:[f('reading1','第一次稳定示值','pH₁','—','一手观测值','7.21'),f('reading2','第二次稳定示值','pH₂','—','一手观测值','7.23'),f('electrodeTemp','电极温度','T','℃','样品与环境','23.0')],results:[{key:'ph',label:'pH检测结果',unit:'—',decimals:2}]},
  {code:'Y02',title:'BOD₅检测记录',shortName:'BOD₅',category:'水质检测',ledgerNo:'CQSWHY2026-Y02',method:'稀释与接种法 · HJ 505—2009',methodVersion:'HJ 505—2009',methodState:'现行方法',formulaVersion:'FX-Y02-V0.1',formulaText:'BOD₅ = [(D₁−D₂)−f(B₁−B₂)] ÷ P',frequency:'日检',existing:false,
    fields:[f('d1','培养前溶解氧','D₁','mg/L','一手观测值','8.20'),f('d2','培养后溶解氧','D₂','mg/L','一手观测值','3.10'),f('b1','接种稀释水培养前DO','B₁','mg/L','标准与试剂','8.30'),f('b2','接种稀释水培养后DO','B₂','mg/L','标准与试剂','7.90'),f('seedFactor','接种液校正系数','f','—','标准与试剂','1'),f('sampleRatio','水样体积分数','P','—','样品与环境','0.10')],results:[{key:'bod5',label:'BOD₅检测结果',unit:'mg/L',decimals:1}]},
  {code:'Y03',title:'COD容量法原始记录',shortName:'COD',category:'水质检测',ledgerNo:'CQSWHY2026-Y03',method:'重铬酸盐法 · HJ 828—2017',methodVersion:'HJ 828—2017',methodState:'现行方法',formulaVersion:'FX-Y03-V0.2',formulaText:'COD = c(V₀−V₁)×8000×n÷V',frequency:'日检',existing:true,
    fields:[...sample,f('titrantConcentration','硫酸亚铁铵浓度','c','mol/L','标准与试剂','0.0500'),f('blankVolume','空白滴定体积','V₀','mL','一手观测值','24.50'),f('sampleTitration','样品滴定体积','V₁','mL','一手观测值','21.10')],results:[{key:'cod',label:'COD检测结果',unit:'mg/L',decimals:1}]},
  {code:'Y04',title:'SS重量法原始记录',shortName:'SS',category:'水质检测',ledgerNo:'CQSWHY2026-Y04',method:'重量法 · GB 11901—89',methodVersion:'GB 11901—89',methodState:'现行方法',formulaVersion:'FX-Y04-V0.2',formulaText:'SS = (m₂−m₁)×1,000,000÷V',frequency:'日检',existing:true,
    fields:[f('sampleVolume','取样体积','V','mL','样品与环境','100'),f('tare1','滤膜恒重第一次','m₁-1','g','一手观测值','0.0678'),f('tare2','滤膜恒重第二次','m₁-2','g','一手观测值','0.0677'),f('loaded1','载样恒重第一次','m₂-1','g','一手观测值','0.0741'),f('loaded2','载样恒重第二次','m₂-2','g','一手观测值','0.0740')],results:[{key:'ss',label:'SS检测结果',unit:'mg/L',decimals:1}]},
  {code:'Y05',title:'总磷（分光光度法）检测记录',shortName:'总磷',category:'水质检测',ledgerNo:'CQSWHY2026-Y05',method:'钼酸铵分光光度法 · GB 11893—89',methodVersion:'GB 11893—89',methodState:'现行方法',formulaVersion:'FX-Y05-V0.1',formulaText:'m=(A−A₀−b)÷a；ρ=m×n÷V',frequency:'日检',existing:false,
    fields:[...sample,f('sampleAbsorbance','样品吸光度','A','Abs','一手观测值','0.265'),...curve],results:spectroResults},
  {code:'Y06',title:'氨氮（分光光度法）检测记录',shortName:'氨氮',category:'水质检测',ledgerNo:'CQSWHY2026-Y06',method:'纳氏试剂分光光度法 · HJ 535—2009',methodVersion:'HJ 535—2009',methodState:'现行方法',formulaVersion:'FX-Y06-V0.2',formulaText:'m=(A−A₀−b)÷a；ρ=m×n÷V',frequency:'日检',existing:true,
    fields:[...sample,f('sampleAbsorbance','样品吸光度','A','Abs','一手观测值','0.203'),...curve],results:spectroResults},
  {code:'Y07',title:'硝酸盐氮检测记录',shortName:'硝酸盐氮',category:'水质检测',ledgerNo:'CQSWHY2026-Y07',method:'项目方法 · 紫外校正法（适用性待确认）',methodVersion:'项目方法-PENDING',methodState:'待确认',formulaVersion:'FX-Y07-V0.1-DRAFT',formulaText:'A校正=A₂₂₀−2A₂₇₅；m=(A校正−b)÷a；ρ=m×n÷V',frequency:'日检',existing:false,scopeNote:'原汇总所列 HJ/T 346—2007 适用范围与污水样品不完全匹配；暂按项目方法展示，不作为正式现行标准。',
    fields:[...sample,f('a220','220 nm吸光度','A₂₂₀','Abs','一手观测值','0.310'),f('a275','275 nm吸光度','A₂₇₅','Abs','一手观测值','0.026'),f('curveSlope','项目曲线斜率','a','Abs/μg','标准与试剂','0.0100'),f('curveIntercept','项目曲线截距','b','Abs','标准与试剂','0.002')],results:[{key:'correctedAbsorbance',label:'校正吸光度',unit:'Abs',decimals:3},...spectroResults]},
  {code:'Y08',title:'总氮（分光光度法）检测记录',shortName:'总氮',category:'水质检测',ledgerNo:'CQSWHY2026-Y08',method:'碱性过硫酸钾消解紫外分光光度法 · HJ 636—2012',methodVersion:'HJ 636—2012',methodState:'现行方法',formulaVersion:'FX-Y08-V0.1',formulaText:'A校正=A₂₂₀−2A₂₇₅；m=(A校正−b)÷a；ρ=m×n÷V',frequency:'日检',existing:false,
    fields:[...sample,f('a220','220 nm吸光度','A₂₂₀','Abs','一手观测值','0.342'),f('a275','275 nm吸光度','A₂₇₅','Abs','一手观测值','0.031'),f('curveSlope','标准曲线斜率','a','Abs/μg','标准与试剂','0.0098'),f('curveIntercept','标准曲线截距','b','Abs','标准与试剂','0.002')],results:[{key:'correctedAbsorbance',label:'校正吸光度',unit:'Abs',decimals:3},...spectroResults]},
  {code:'Y09',title:'粪大肠菌群（滤膜法）检测记录',shortName:'粪大肠菌群',category:'水质检测',ledgerNo:'CQSWHY2026-Y09',method:'滤膜法 · HJ 347.1—2018',methodVersion:'HJ 347.1—2018',methodState:'现行方法',formulaVersion:'FX-Y09-V0.2',formulaText:'菌群数 = 菌落数×1000×n÷V',frequency:'日检',existing:true,
    fields:[...sample,f('colonyCount','滤膜菌落数','N','个','一手观测值','3'),f('cultureTemperature','培养温度','T','℃','样品与环境','44.5'),f('cultureHours','培养时间','t','h','样品与环境','24')],results:[{key:'fc',label:'粪大肠菌群',unit:'个/L',decimals:0}]},
  {code:'Y10',title:'活性污泥指标检测记录（MLSS/MLVSS）',shortName:'活性污泥',category:'污泥检测',ledgerNo:'CQSWHY2026-Y10',method:'重量法/体积法 · CJ/T 221—2023',methodVersion:'CJ/T 221—2023',methodState:'现行方法',formulaVersion:'FX-Y10-V0.1',formulaText:'MLSS=(m₂−m₁)×10⁶÷V；MLVSS=(m₂−m₃)×10⁶÷V；SVI=SV₃₀×10⁴÷MLSS',frequency:'日检/周检',existing:false,
    fields:[f('sampleVolume','混合液体积','V','mL','样品与环境','100'),f('sv30','30 min沉降体积比','SV₃₀','%','一手观测值','28'),f('tareMass','坩埚/滤膜恒重','m₁','g','一手观测值','0.0680'),f('dryMass','干燥后总重','m₂','g','一手观测值','0.3280'),f('ignitedMass','灼烧后总重','m₃','g','一手观测值','0.1190')],results:[{key:'mlss',label:'MLSS',unit:'mg/L',decimals:0},{key:'mlvss',label:'MLVSS',unit:'mg/L',decimals:0},{key:'svI',label:'SVI',unit:'mL/g',decimals:1},{key:'ratio',label:'MLVSS/MLSS',unit:'%',decimals:1}]},
  {code:'Y11',title:'污泥（泥饼）指标检测记录',shortName:'泥饼指标',category:'污泥检测',ledgerNo:'CQSWHY2026-Y11',method:'含水率/有机物 · CJ/T 221—2023',methodVersion:'CJ/T 221—2023',methodState:'现行方法',formulaVersion:'FX-Y11-V0.1',formulaText:'含水率=(m湿−m干)÷(m湿−m皿)×100%；有机物=(m干−m灰)÷(m干−m皿)×100%',frequency:'日检',existing:false,
    fields:[f('tareMass','蒸发皿恒重','m₀','g','一手观测值','42.180'),f('wetMass','皿加湿样质量','m湿','g','一手观测值','92.180'),f('dryMass','皿加干样质量','m干','g','一手观测值','51.680'),f('ashMass','灼烧后质量','m灰','g','一手观测值','47.120')],results:[{key:'moisture',label:'含水率',unit:'%',decimals:1},{key:'organic',label:'有机物含量',unit:'%',decimals:1}]},
  {code:'Y12',title:'正磷酸盐（分光光度法）检测记录',shortName:'正磷酸盐',category:'水质检测',ledgerNo:'CQSWHY2026-Y12',method:'项目方法 · 钼酸铵分光光度法',methodVersion:'项目方法-V0.1',methodState:'项目方法',formulaVersion:'FX-Y12-V0.1',formulaText:'m=(A−A₀−b)÷a；ρ=m×n÷V',frequency:'周检',existing:false,scopeNote:'结果暂以 P 计；后续确认是否同时展示 PO₄³⁻折算值。',
    fields:[...sample,f('sampleAbsorbance','样品吸光度','A','Abs','一手观测值','0.126'),...curve],results:spectroResults},
  {code:'Y13',title:'碱度（容量法）原始记录',shortName:'碱度',category:'水质检测',ledgerNo:'CQSWHY2026-Y13',method:'项目方法 · 酸碱滴定（依据待确认）',methodVersion:'项目方法-PENDING',methodState:'待确认',formulaVersion:'FX-Y13-V0.1-DRAFT',formulaText:'碱度（以CaCO₃计）=(Vₚ+Vₘ)c×50,000×n÷V',frequency:'周检',existing:false,scopeNote:'原汇总所列 HJ 821—2017 并非碱度方法；当量基准和项目方法待确认。',
    fields:[...sample,f('phenolphthaleinVolume','酚酞终点耗酸量','Vₚ','mL','一手观测值','0.20'),f('methylOrangeVolume','甲基橙终点耗酸量','Vₘ','mL','一手观测值','3.40'),f('acidConcentration','标准酸浓度','c','mol/L','标准与试剂','0.0200')],results:[{key:'alkalinity',label:'总碱度（以CaCO₃计）',unit:'mg/L',decimals:1}]},
  {code:'Y14',title:'氯化物（容量法）原始记录',shortName:'氯化物',category:'水质检测',ledgerNo:'CQSWHY2026-Y14',method:'硝酸银滴定法 · GB/T 11896—1989',methodVersion:'GB/T 11896—1989',methodState:'现行方法',formulaVersion:'FX-Y14-V0.1',formulaText:'Cl⁻=(Vₛ−Vᵦ)c×35,450×n÷V',frequency:'周检',existing:false,
    fields:[...sample,f('sampleTitration','样品耗硝酸银量','Vₛ','mL','一手观测值','3.80'),f('blankVolume','空白耗硝酸银量','Vᵦ','mL','一手观测值','0.10'),f('silverConcentration','硝酸银浓度','c','mol/L','标准与试剂','0.0141')],results:[{key:'chloride',label:'氯化物',unit:'mg/L',decimals:1}]},
  {code:'Y15',title:'总盐量（重量法）原始记录',shortName:'总盐量',category:'水质检测',ledgerNo:'CQSWHY2026-Y15',method:'总盐量 · HJ 51—2024（项目范围待确认）',methodVersion:'HJ 51—2024/项目确认',methodState:'待确认',formulaVersion:'FX-Y15-V0.1-DRAFT',formulaText:'总盐量=(m₂−m₁)×1,000,000×n÷V',frequency:'周检',existing:false,scopeNote:'HJ 51—2024 对应总盐量，不等同于总固体或溶解性总固体；是否拆分三个项目待确认。',
    fields:[...sample,f('tareMass','蒸发皿恒重','m₁','g','一手观测值','42.1800'),f('dryMass','蒸干后总重','m₂','g','一手观测值','42.1982')],results:[{key:'totalSalts',label:'总盐量',unit:'mg/L',decimals:1}]},
  {code:'Y16',title:'PAC药剂原始记录',shortName:'PAC',category:'药剂检测',ledgerNo:'CQSWHY2026-Y16',method:'氧化铝 · GB/T 22627—2022',methodVersion:'GB/T 22627—2022',methodState:'现行方法',formulaVersion:'FX-Y16-V0.2',formulaText:'Al₂O₃=[(V₀−V)cM/2]×10⁻³÷[mV₁/Vₐ]×100%',frequency:'药剂检测',existing:false,scopeNote:'本页按提供的药剂原始记录实现氧化铝与密度；盐基度需补充对应原始滴定字段后启用，不使用暂定公式。',
    fields:[f('sampleMass','试样质量','m','g','样品与环境','5.0000'),f('aliquotVolume','移取试液体积','V₁','mL','样品与环境','5.00'),f('flaskVolume','试液定容体积','Vₐ','mL','样品与环境','250.00'),f('zincConcentration','氯化锌标准液浓度','c','mol/L','标准与试剂','0.0163'),f('blankVolume','空白滴定体积','V₀','mL','一手观测值','50.70'),f('sampleTitration','样品滴定体积','V','mL','一手观测值','35.20'),f('density','密度','ρ','g/mL','一手观测值','1.209')],results:[{key:'alumina',label:'氧化铝含量',unit:'%',decimals:2},{key:'densityResult',label:'密度',unit:'g/mL',decimals:3}]},
  {code:'Y17',title:'次氯酸钠（碘量法）原始记录',shortName:'次氯酸钠',category:'药剂检测',ledgerNo:'CQSWHY2026-Y17',method:'碘量法 · GB/T 19106—2013',methodVersion:'GB/T 19106—2013',methodState:'现行方法',formulaVersion:'FX-Y17-V0.2',formulaText:'有效氯=cV×0.03545÷[m×10/500]×100%；密度为一手读数',frequency:'药剂检测',existing:false,
    fields:[f('sampleMass','试样净质量','m','g','样品与环境','24.2204'),f('thioConcentration','硫代硫酸钠浓度','c','mol/L','标准与试剂','0.1007'),f('sampleTitration','滴定体积','V','mL','一手观测值','16.60'),f('density','密度','ρ','g/mL','一手观测值','1.219')],results:[{key:'availableChlorine',label:'有效氯',unit:'%',decimals:2},{key:'densityResult',label:'密度',unit:'g/mL',decimals:3}]},
  {code:'Y18',title:'碳源（容量法）原始记录',shortName:'碳源',category:'药剂检测',ledgerNo:'CQSWHY2026-Y18',method:'项目方法 · 按产品类型受控选择',methodVersion:'项目方法-PENDING',methodState:'待确认',formulaVersion:'FX-Y18-V0.2-DRAFT',formulaText:'乙酸含量=cV×60.05÷(m×1000)×100%；其他产品按各自受控方法',frequency:'药剂检测',existing:false,scopeNote:'冰醋酸、乙酸钠及复合碳源不能共用一个固定标准；当前演示公式仅适用于冰醋酸，产品类型与合同技术指标待确认。',
    fields:[f('productType','碳源产品类型','—','—','样品与环境','冰醋酸',{inputType:'select',options:[{label:'冰醋酸（当前演示）',value:'冰醋酸'},{label:'乙酸钠（待确认）',value:'乙酸钠'},{label:'复合碳源（项目方法）',value:'复合碳源'}]}),f('sampleMass','试样质量','m','g','样品与环境','2.0200'),f('alkaliConcentration','氢氧化钠浓度','c','mol/L','标准与试剂','1.0090'),f('sampleTitration','滴定体积','V','mL','一手观测值','33.30'),f('codEquivalent','同批次COD检测结果','COD','mg/g','一手观测值','1067',{hint:'来自同批次受控COD原始记录；正式版改为自动关联'}),f('density','密度','ρ','g/mL','一手观测值','1.080')],results:[{key:'content',label:'乙酸含量（仅冰醋酸）',unit:'%',decimals:2},{key:'codEquivalentResult',label:'同批次COD',unit:'mg/g',decimals:0},{key:'densityResult',label:'密度',unit:'g/mL',decimals:3}]},
]

export const templateByCode = Object.fromEntries(labTemplates.map(item=>[item.code,item])) as Record<LabTemplateCode,LabTemplate>
export const labCategories = ['水质检测','污泥检测','药剂检测'] as const
