package com.waterx.safety.investment;

import com.waterx.safety.auth.CurrentUser;import com.waterx.safety.site.SiteAccessService;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.annotation.AuthenticationPrincipal;import org.springframework.web.bind.annotation.*;import java.math.BigDecimal;import java.time.LocalDate;import java.util.*;

@RestController @RequestMapping("/api/v1/safety/investment")
public class SafetyInvestmentController{
 private final JdbcClient jdbc;private final SiteAccessService sites;public SafetyInvestmentController(JdbcClient j,SiteAccessService s){jdbc=j;sites=s;}
 @GetMapping("/summary") @PreAuthorize("hasAuthority('inspection:read')") Summary summary(@AuthenticationPrincipal CurrentUser u,@RequestHeader("X-Site-Id")UUID s,@RequestParam(required=false)Integer year){sites.requireSiteAccess(u,s);int y=year==null?LocalDate.now().getYear():year;return jdbc.sql("select coalesce(sum(p.planned_amount),0),coalesce((select sum(e.amount) from safety_expense e join safety_budget_plan b on b.tenant_id=e.tenant_id and b.id=e.budget_id where e.tenant_id=:t and e.site_id=:s and b.budget_year=:y),0) from safety_budget_plan p where p.tenant_id=:t and p.site_id=:s and p.budget_year=:y").param("t",u.tenantId()).param("s",s).param("y",y).query((r,n)->{BigDecimal planned=r.getBigDecimal(1),spent=r.getBigDecimal(2);return new Summary(y,planned,spent,planned.subtract(spent),planned.signum()==0?BigDecimal.ZERO:spent.multiply(BigDecimal.valueOf(100)).divide(planned,2,java.math.RoundingMode.HALF_UP));}).single();}
 @GetMapping("/budgets") @PreAuthorize("hasAuthority('inspection:read')") List<Budget> budgets(@AuthenticationPrincipal CurrentUser u,@RequestHeader("X-Site-Id")UUID s){sites.requireSiteAccess(u,s);return jdbc.sql("select p.id,p.budget_year,p.category,p.planned_amount,p.description,p.status,coalesce(sum(e.amount),0) spent from safety_budget_plan p left join safety_expense e on e.tenant_id=p.tenant_id and e.budget_id=p.id where p.tenant_id=:t and p.site_id=:s group by p.id order by p.budget_year desc,p.category").param("t",u.tenantId()).param("s",s).query((r,n)->new Budget(r.getObject(1,UUID.class),r.getInt(2),r.getString(3),r.getBigDecimal(4),r.getString(5),r.getString(6),r.getBigDecimal(7))).list();}
 @GetMapping("/expenses") @PreAuthorize("hasAuthority('inspection:read')") List<Expense> expenses(@AuthenticationPrincipal CurrentUser u,@RequestHeader("X-Site-Id")UUID s){sites.requireSiteAccess(u,s);return jdbc.sql("select e.id,b.category,e.expense_date,e.amount,e.purpose,e.vendor,e.invoice_no,e.recorded_by from safety_expense e join safety_budget_plan b on b.tenant_id=e.tenant_id and b.id=e.budget_id where e.tenant_id=:t and e.site_id=:s order by e.expense_date desc").param("t",u.tenantId()).param("s",s).query((r,n)->new Expense(r.getObject(1,UUID.class),r.getString(2),r.getObject(3,LocalDate.class),r.getBigDecimal(4),r.getString(5),r.getString(6),r.getString(7),r.getString(8))).list();}
 @PostMapping("/budgets") @PreAuthorize("hasAuthority('inspection:manage')") Id budget(@AuthenticationPrincipal CurrentUser u,@RequestHeader("X-Site-Id")UUID s,@Valid @RequestBody BudgetInput in){sites.requireSiteAccess(u,s);UUID id=UUID.randomUUID();jdbc.sql("insert into safety_budget_plan(id,tenant_id,site_id,budget_year,category,planned_amount,description,status) values(:id,:t,:s,:year,:category,:amount,:description,'APPROVED')").param("id",id).param("t",u.tenantId()).param("s",s).param("year",in.budgetYear()).param("category",in.category()).param("amount",in.plannedAmount()).param("description",in.description()).update();return new Id(id);}
 @PostMapping("/expenses") @PreAuthorize("hasAuthority('inspection:manage')") Id expense(@AuthenticationPrincipal CurrentUser u,@RequestHeader("X-Site-Id")UUID s,@Valid @RequestBody ExpenseInput in){sites.requireSiteAccess(u,s);UUID id=UUID.randomUUID();jdbc.sql("insert into safety_expense(id,tenant_id,site_id,budget_id,expense_date,amount,purpose,vendor,invoice_no,recorded_by) values(:id,:t,:s,:budget,:date,:amount,:purpose,:vendor,:invoice,:by)").param("id",id).param("t",u.tenantId()).param("s",s).param("budget",in.budgetId()).param("date",in.expenseDate()).param("amount",in.amount()).param("purpose",in.purpose()).param("vendor",in.vendor()).param("invoice",in.invoiceNo()).param("by",in.recordedBy()).update();return new Id(id);}
 public record Summary(int year,BigDecimal plannedAmount,BigDecimal spentAmount,BigDecimal remainingAmount,BigDecimal executionRate){}public record Budget(UUID id,int budgetYear,String category,BigDecimal plannedAmount,String description,String status,BigDecimal spentAmount){}public record Expense(UUID id,String category,LocalDate expenseDate,BigDecimal amount,String purpose,String vendor,String invoiceNo,String recordedBy){}public record BudgetInput(@Min(2000) int budgetYear,@NotBlank String category,@Positive BigDecimal plannedAmount,@NotBlank String description){}public record ExpenseInput(@NotNull UUID budgetId,@NotNull LocalDate expenseDate,@Positive BigDecimal amount,@NotBlank String purpose,String vendor,String invoiceNo,@NotBlank String recordedBy){}public record Id(UUID id){}
}
