spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 110MB

server:
  forward-headers-strategy: framework
  shutdown: graceful

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

management:
  endpoint:
    health:
      show-details: never
  endpoints:
    web:
      exposure:
        include: health

app:
  storage:
    local-dir: ${FILE_STORAGE_DIR}
