import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import { createRequire } from 'node:module'
import { fileURLToPath } from 'node:url'
const require = createRequire(import.meta.url), ts = require('typescript'), Module = require('node:module')
const dir = path.dirname(fileURLToPath(import.meta.url)), cache = new Map()
function load(name, from = dir) {
  const file = path.resolve(from, name + '.ts')
  if (cache.has(file)) return cache.get(file).exports
  const m = new Module(file); m.filename = file; m.paths = Module._nodeModulePaths(path.dirname(file))
  m.require = id => id.startsWith('.') ? load(id, path.dirname(file)) : require(id); cache.set(file, m)
  m._compile(ts.transpileModule(fs.readFileSync(file, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText, file)
  return m.exports
}
const { emptyDraft, newFact } = load('./types'), { waterAnalysis } = load('./water'), { readFact, number } = load('./calculation'), storage = load('./storage')
let count = 0
function test(name, work) { work(); count++; console.log(`PASS ${name}`) }
function fact(d, name, role, value, extra = {}) { return { ...newFact(d.date, role, 'm³'), name, path: name, source: '独立测试凭据', values: { value: String(value) }, ...extra } }
function water() {
  const d = emptyDraft('water'); d.complete = true; d.basis = 'W01完整边界'; d.facts = [fact(d, '进水', 'IN', 10000), fact(d, '出水', 'OUT', 9700), fact(d, '回水', 'INTERNAL', 800), fact(d, '库存', 'STOCK', 0, { values: { start: '1000', end: '1200' } })]; return d
}
const metric = (d, id) => waterAnalysis(d).metrics.find(m => m.id === id)
test('W01 外入不含回水、差额100、比例1%、回水比8%', () => { const d = water(); for (const [id, n] of [['WB-02', 10000], ['WB-05', 100], ['WB-06', 1], ['WB-07', 8]]) assert.equal(metric(d, id).value, n) })
test('W02 库存减少合法', () => { const d = water(); d.facts[1].values.value = '10100'; d.facts[3].values.end = '900'; assert.equal(metric(d, 'WB-05').value, 0) })
test('W03 适用流向缺失不当0', () => { const d = water(); d.facts.push(fact(d, '回用', 'OUT', '')); assert.equal(metric(d, 'WB-05').value, null); assert.match(metric(d, 'WB-03').note, /9700/) })
test('W04 真0差额有效但除0比例无效', () => { const d = water(); d.facts[0].values.value = d.facts[1].values.value = '0'; d.facts[3].values.end = '1000'; assert.equal(metric(d, 'WB-05').value, 0); assert.equal(metric(d, 'WB-06').status, 'INVALID') })
test('W05 总支路不能双选；关闭支路后恢复', () => { const d = water(); d.facts.push(fact(d, '回用支路', 'OUT', 700, { parent: d.facts[1].id })); assert.equal(metric(d, 'WB-03').status, 'INVALID'); d.facts[4].selected = false; assert.equal(metric(d, 'WB-03').value, 9700) })
test('W06 读数倍率必填、倒转不取绝对值', () => { const d = water(), f = fact(d, '表', 'IN', 0, { method: 'METER', values: { start: '100', end: '110', multiplier: '2' } }); assert.equal(readFact(f, d, 'm³').value, 20); f.values.multiplier = ''; assert.equal(readFact(f, d, 'm³').value, null); f.values.multiplier = '2'; f.values.end = '90'; assert.equal(readFact(f, d, 'm³').status, 'INVALID') })
test('W07 串联内部回水不能重复求和', () => { const d = water(); d.facts.push(fact(d, '回水下游', 'INTERNAL', 800, { path: '回水' })); assert.equal(metric(d, 'WB-07').value, null); assert.equal(metric(d, 'WB-05').value, 100) })
test('空白/限定符/非法数值不是0', () => { for (const x of ['', ' ', '<0.02', 'Infinity', '3abc']) assert.equal(number(x), null); assert.equal(number('0'), 0) })
test('没有边界确认不出完整差额', () => { const d = water(); d.complete = false; assert.equal(metric(d, 'WB-05').value, null); assert.equal(metric(d, 'WB-02').value, 10000) })
test('库存负值拒绝而负变化允许', () => { const d = water(); d.facts[3].values.start = '-1'; assert.equal(metric(d, 'WB-04').status, 'INVALID') })
test('不适用需依据，可排除未知候选', () => { const d = water(); d.facts.push(fact(d, '无厂外回用', 'OUT', '', { state: 'NA', note: '' })); assert.equal(metric(d, 'WB-03').status, 'INVALID'); d.facts[4].note = '已核实无此出口'; assert.equal(metric(d, 'WB-03').value, 9700) })
test('错误单位和跨日阻止计算', () => { const d = water(); d.facts[0].unit = '万m³'; assert.equal(metric(d, 'WB-02').value, null); d.facts[0].unit = 'm³'; d.facts[0].date = '2025-01-01'; assert.equal(metric(d, 'WB-02').value, null) })
test('估算状态向依赖结果传播', () => { const d = water(); d.facts[0].state = 'ESTIMATED'; assert.equal(metric(d, 'WB-05').status, 'ESTIMATED') })
test('包含关系成环阻止核算', () => { const d = water(); d.facts[0].parent = d.facts[1].id; d.facts[1].parent = d.facts[0].id; assert.equal(metric(d, 'WB-02').value, null) })
test('缺少整个库存组不能自动0', () => { const d = water(); d.facts = d.facts.filter(f => f.role !== 'STOCK'); assert.equal(metric(d, 'WB-05').value, null) })
test('无项目阈值不显示合格或泄漏', () => { const d = water(); assert.ok(waterAnalysis(d).issues.some(x => x.includes('待确认'))); d.parameters = { limit: '50', targetSource: '项目审核' }; d.checks.target = true; assert.ok(waterAnalysis(d).issues.some(x => x.includes('超过项目'))) })
const map = new Map(), mem = { getItem: k => map.get(k) ?? null, setItem: (k, v) => map.set(k, v) }
let archive = storage.loadArchive('A', mem)
test('保存回读、同日两版本旧快照不变', () => { const d = water(); archive = storage.saveSnapshot(archive, d, waterAnalysis(d), '测试人', '首次', mem); d.facts[0].values.value = '11000'; archive = storage.saveSnapshot(archive, d, waterAnalysis(d), '测试人', '更正', mem); assert.equal(archive.snapshots[1].version, 2); assert.equal(archive.snapshots[0].result.metrics.find(m => m.id === 'WB-02').value, 10000); assert.deepEqual(storage.loadArchive('A', mem), archive) })
test('跨项目隔离', () => assert.equal(storage.loadArchive('B', mem).snapshots.length, 0))
test('旧窗口并发写拦截、无原因拦截', () => { const d = water(); assert.throws(() => storage.saveSnapshot({ ...archive, revision: 0 }, d, waterAnalysis(d), '测试', '原因', mem), /其他窗口/); assert.throws(() => storage.saveSnapshot(archive, d, waterAnalysis(d), '测试', '', mem), /原因/) })
test('本地保存失败可见且原档案不变', () => { const d = water(), before = JSON.stringify(archive); assert.throws(() => storage.saveSnapshot(archive, d, waterAnalysis(d), '测试', '原因', { ...mem, setItem() { throw new Error('容量不足') } }), /容量/); assert.equal(JSON.stringify(archive), before) })
test('来源版本更正仅提示不改历史快照', () => { const d = water(); const id = '水量控制::日进水量'; d.facts[0].reference = { entryId: 'e1', metricId: id, version: 1, original: '1', factor: 10000, line: '一期' }; map.set('waterx-process-mvp-v1:A', JSON.stringify({ schema: 1, revision: 1, siteId: 'A', designs: [], conditions: [], diagnoses: [], entries: [{ id: 'e1', date: d.date, line: '一期', versions: [{ version: 2, demo: false, cells: { [id]: { value: '2', state: 'VALID' } } }] }] })); assert.equal(storage.sourceChanges('A', d, mem).length, 1); assert.equal(d.facts[0].values.value, '10000') })
const { energyAnalysis, periodIntensity } = load('./energy'), { sludgeAnalysis, solidFact } = load('./sludge'), { demoDraft } = load('./definitions')
const en = (d, id) => energyAnalysis(d).metrics.find(m => m.id === id)
test('E01 总表独立、互斥分项700、差额300', () => { const d = demoDraft('energy'); assert.equal(en(d, 'EN-02').value, 1000); assert.equal(en(d, 'EN-04').value, 700); assert.equal(en(d, 'EN-05').value, 300) })
test('E02 有电无水保留电量', () => { const d = demoDraft('energy'); assert.equal(en(d, 'EN-03').value, .2); d.facts[3].values.value = ''; assert.equal(en(d, 'EN-02').value, 1000); assert.equal(en(d, 'EN-03').value, null) })
test('E03 实测400、估算300、未知300', () => { const d = demoDraft('energy'); d.facts[2].state = 'ESTIMATED'; assert.equal(en(d, 'EN-04').value, 400); assert.equal(en(d, 'EN-05').value, 600); assert.equal(en(d, 'EN-UNKNOWN').value, 300) })
test('E04 子表超过总表保留负差额', () => { const d = demoDraft('energy'); d.facts[1].values.value = '700'; d.facts[2].values.value = '500'; assert.equal(en(d, 'EN-05').value, -200) })
test('E05 费用因素−60与+90不冒充收益', () => { const d = demoDraft('energy'); d.facts[0].values.value = '900'; d.checks.price = true; d.parameters = { price: '.7', previousEnergy: '1000', previousPrice: '.6', costSource: '两期人工验算' }; assert.equal(en(d, 'EN-09-E').value, -60); assert.ok(Math.abs(en(d, 'EN-09-P').value - 90) < 1e-10); assert.equal(en(d, 'EN-08').value, 630) })
test('E06 周期单耗不平均日比值，缺日返回空', () => { assert.equal(periodIntensity([{ energy: 100, water: 100 }, { energy: 100, water: 900 }]), .2); assert.equal(periodIntensity([{ energy: null, water: 100 }]), null) })
test('E07 零电耗有效、零水量无效、缺电量缺失', () => { const d = demoDraft('energy'); d.facts[0].values.value = '0'; assert.equal(en(d, 'EN-03').value, 0); d.facts[3].values.value = '0'; assert.equal(en(d, 'EN-03').status, 'INVALID'); d.facts[0].values.value = ''; assert.equal(en(d, 'EN-02').status, 'MISSING') })
test('E08 同日约束不接受其他周期冒作日数据', () => { const d = demoDraft('energy'); d.facts[0].date = '2026-09'; assert.equal(en(d, 'EN-02').value, null) })
test('电表子项互相包含时只阻止分项，不封锁有效总表', () => { const d = demoDraft('energy'); d.facts[2].parent = d.facts[1].id; assert.equal(en(d, 'EN-04').value, null); assert.equal(en(d, 'EN-02').value, 1000) })
const sb = (d, id) => sludgeAnalysis(d).metrics.find(m => m.id === id)
test('S01 液态DS单位换算等价', () => { const d = demoDraft('sludge'), f = d.facts[0]; f.values.value = '100'; f.unit = 'mg/L'; f.values.concentration = '10000'; assert.equal(solidFact(f, d).value, 1); f.unit = 'kg/m³'; f.values.concentration = '10'; assert.equal(solidFact(f, d).value, 1) })
test('S02 湿50含水80得到干10', () => { const d = demoDraft('sludge'); d.facts[2].values.value = '50'; assert.ok(Math.abs(solidFact(d.facts[2], d).value - 10) < 1e-12) })
test('S03 逐车先算固体再加权含水率', () => { const d = demoDraft('sludge'); d.facts[2].values.value = '10'; d.facts.push({ ...d.facts[2], id: 'truck2', name: '车2', path: '车2', values: { value: '30', moisture: '70' } }); assert.ok(Math.abs(sb(d, 'SB09').value - 11) < 1e-12); assert.equal(sb(d, 'SB09-W').value, 72.5) })
test('S04 外加固体、返流、库存、转化完整差额0.3', () => { const d = demoDraft('sludge'); assert.ok(Math.abs(sb(d, 'SB06').value - .3) < 1e-12); assert.ok(Math.abs(sb(d, 'SB07').value - .3 / 10.5 * 100) < 1e-10) })
test('S05 库存未知不能闭合', () => { const d = demoDraft('sludge'); d.facts[4].values.end = ''; assert.equal(sb(d, 'SB06').value, null); assert.ok(sb(d, 'SB09').value > 0) })
test('S06 外运大于输入但消耗库存，差额仍可0', () => { const d = demoDraft('sludge'); d.facts[1].values.value = '0'; d.facts[2].values.value = '60'; d.facts[3].values.concentration = '0'; d.facts[4].values = { start: '2', end: '0' }; assert.ok(Math.abs(sb(d, 'SB06').value) < 1e-12) })
test('S07 内部转移不计新输入，重复外来路径阻止', () => { const d = demoDraft('sludge'); d.facts.push({ ...d.facts[0], id: 'internal', role: 'INTERNAL' }); assert.equal(sb(d, 'SB04').value, 10.5); d.facts.at(-1).role = 'IN'; assert.equal(sb(d, 'SB04').value, null) })
test('S08 同干量减湿量不改干固体', () => { const d = demoDraft('sludge'); d.facts[2].values = { value: '40', moisture: '75' }; assert.equal(solidFact(d.facts[2], d).value, 10) })
test('S09 返流氨氮20kg与固体浓度独立', () => { const d = demoDraft('sludge'); d.facts[3].values.concentration = ''; assert.equal(sb(d, d.facts[3].id + '-N').value, 20); assert.equal(sb(d, 'SB06').value, null) })
test('S10 库存5净积存1得到5天，必须标情景估算', () => { const d = demoDraft('sludge'); d.parameters = { remaining: '5', accumulation: '1' }; d.checks.stable = true; assert.equal(sb(d, 'SB12').value, 5); assert.equal(sb(d, 'SB12').status, 'ESTIMATED'); d.checks.stable = false; assert.equal(sb(d, 'SB12').value, null) })
test('S11 产率1×6小时对需求8得到缺口2', () => { const d = demoDraft('sludge'); d.parameters = { rate: '1', hours: '6', demand: '8', capacitySource: '独立核验' }; d.checks.capacity = true; assert.equal(sb(d, 'SB11').value, 6); assert.equal(sb(d, 'SB11-GAP').value, 2); d.parameters.hours = '25'; assert.equal(sb(d, 'SB11').value, null) })
test('S12 同源推算不能自证闭合', () => { const d = demoDraft('sludge'); d.checks.independent = false; assert.equal(sb(d, 'SB06').value, null) })
test('S13 SS/TS差异未确认，不给严格平衡', () => { const d = demoDraft('sludge'); d.checks.solids = false; assert.equal(sb(d, 'SB06').value, null) })
test('S14 仅商品药量不得按干固体量计入', () => { const d = demoDraft('sludge'); d.facts[1].unit = 'kg商品'; assert.equal(sb(d, 'SB04').value, null) })
const { chemicalAnalysis } = load('./chemical'), { capacityAnalysis } = load('./capacity'), { hydraulicAnalysis } = load('./hydraulic')
const ch = (d, id) => chemicalAnalysis(d).metrics.find(m => m.id === id), cp = (d, id) => capacityAnalysis(d).metrics.find(m => m.id === id), hy = (d, id) => hydraulicAnalysis(d).metrics.find(m => m.id === id)
test('药剂1000kg×10%=100kg，10000m³为10mg/L', () => { const d = demoDraft('chemical'); assert.equal(ch(d, d.facts[0].id + '-active').value, 100); assert.equal(ch(d, d.facts[0].id + '-dose').value, 10) })
test('采购/领用不冒充实际投加或费用', () => { const d = demoDraft('chemical'); d.facts[0].role = 'PURCHASE'; assert.equal(ch(d, 'CH-COST').value, null); assert.ok(!ch(d, d.facts[0].id + '-dose')) })
test('体积缺密度不能算质量，密度齐后换算', () => { const d = demoDraft('chemical'); d.facts[0].unit = 'L'; d.facts[0].method = 'VOLUME'; assert.equal(ch(d, d.facts[0].id).value, null); d.facts[0].values.density = '1.2'; assert.equal(ch(d, d.facts[0].id).value, 1200) })
test('碳源纯度不能替代有效当量', () => { const d = demoDraft('chemical'); d.facts[0].role = 'CARBON'; assert.equal(ch(d, d.facts[0].id + '-active').value, null); d.facts[0].values.equivalence = '0.5'; assert.equal(ch(d, d.facts[0].id + '-active').value, 500) })
test('费用缺价格不当0，零价明确允许', () => { const d = demoDraft('chemical'); d.facts[0].values.price = ''; assert.equal(ch(d, 'CH-COST').value, null); d.facts[0].values.price = '0'; assert.equal(ch(d, 'CH-COST').value, 0) })
test('不同药种有效量分别保留，不产总有效量', () => { const d = demoDraft('chemical'); d.facts.push({ ...d.facts[0], id: 'drug2', name: '药2', path: '药2', values: { value: '1000', active: '20', price: '1' } }); assert.equal(ch(d, 'drug2-active').value, 200); assert.equal(ch(d, 'CH-COST').value, 2000); assert.equal(ch(d, 'CH-ACTIVE'), undefined) })
test('串联1200/1000/1100能力1000，负荷900裕量100', () => { const d = demoDraft('capacity'); assert.equal(cp(d, 'CP-LIMIT-m³/h').value, 1000); assert.equal(cp(d, 'CP-MARGIN-m³/h').value, 100) })
test('关键能力缺失、缺整个阶段不能给完整上限', () => { const d = demoDraft('capacity'); d.facts[1].values.value = ''; assert.equal(cp(d, 'CP-LIMIT-m³/h').value, null); d.facts.splice(1, 1); assert.equal(cp(d, 'CP-LIMIT-m³/h').value, null) })
test('同阶段并联能力相加但受共享上限约束', () => { const d = demoDraft('capacity'); d.facts[1].values = { value: '600', sharedLimit: '950' }; d.facts.push({ ...d.facts[1], id: 'parallel', name: '过滤2', values: { value: '600', sharedLimit: '950' } }); assert.equal(cp(d, 'CP-LIMIT-m³/h').value, 950) })
test('不同量纲不能取一个全厂最小值', () => { const d = demoDraft('capacity'); d.facts[1].unit = 'kg/d'; assert.equal(cp(d, 'CP-LIMIT-m³/h').value, null); assert.equal(cp(d, 'CP-LIMIT-kg/d').value, null) })
test('工况/拓扑未经确认限制结论', () => { const d = demoDraft('capacity'); d.checks.capacity = false; assert.equal(cp(d, 'CP-LIMIT-m³/h').value, null) })
test('水位10.8−10.2=0.6，设计对照非目标判定', () => { const d = demoDraft('hydraulic'); assert.ok(Math.abs(hy(d, d.facts[0].id).value - .6) < 1e-12) })
test('不同高程基准、缺同期条件不计算', () => { const d = demoDraft('hydraulic'); d.checks.datum = false; assert.equal(hy(d, d.facts[0].id).value, null); d.checks.datum = true; d.checks.simultaneous = false; assert.equal(hy(d, d.facts[0].id).value, null) })
test('跨泵段和压力段不套自由水面公式', () => { const d = demoDraft('hydraulic'); for (const method of ['PUMP', 'PRESSURE', 'UNKNOWN']) { d.facts[0].method = method; assert.equal(hy(d, d.facts[0].id).value, null) } })
test('水力能需确认可减少扬程，效率不足不给电量', () => { const d = demoDraft('hydraulic'); d.parameters = { volume: '10000', dh: '1', rho: '1000', g: '9.81', energySource: '独立算例' }; assert.equal(hy(d, 'HY-POTENTIAL').value, null); d.checks.reducible = true; assert.equal(hy(d, 'HY-POTENTIAL').value, 27.25); assert.equal(hy(d, 'HY-ELECTRIC').value, null); d.parameters.efficiency = '0.5'; assert.equal(hy(d, 'HY-ELECTRIC').value, 54.5); assert.equal(hy(d, 'HY-ELECTRIC').status, 'ESTIMATED') })
test('日期/边界/专题归档互不串用', () => { const d = demoDraft('energy'); const next = storage.saveSnapshot(archive, d, energyAnalysis(d), '测试', '能效', mem); assert.equal(next.snapshots.at(-1).version, 1); assert.equal(next.snapshots.filter(s => s.draft.topic === 'water').length, 2) })
test('污泥批次必须完成整周期，资源口径确认后才算', () => { const d = demoDraft('sludge'); d.checks = { ...d.checks, capacity: true, batch: true, resources: true, costs: true }; d.parameters = { batchDS: '2', hours: '7', cycle: '3', capacitySource: '批次核验', processedDS: '2', energy: '100', actualDrug: '3', electricityFee: '80', drugFee: '40', transportFee: '120', resourceSource: '同设备同周期独立凭据' }; assert.equal(sb(d, 'SB11').value, 4); assert.equal(sb(d, 'SB13-E').value, 50); assert.equal(sb(d, 'SB13-D').value, 1.5); assert.equal(sb(d, 'SB14').value, 240); d.parameters.drugFee = ''; assert.equal(sb(d, 'SB14').value, null) })
test('不相关内部回水配置异常不阻止外部水量核算', () => { const d=water(); d.facts[2].parent=d.facts[2].id; assert.equal(metric(d,'WB-05').value,100); assert.equal(metric(d,'WB-07').value,null) })
test('能力质量量纲相同仍不能混比不同污染物', () => { const d=demoDraft('capacity'); d.facts.forEach(f=>{f.unit='kg/d';f.values.substance='COD'}); assert.equal(cp(d,'CP-LIMIT-kg/d').value,1000); d.facts[1].values.substance='TP'; assert.equal(cp(d,'CP-LIMIT-kg/d').value,null) })
test('共享限制输入非法不能默默忽略', () => { const d=demoDraft('capacity'); d.facts[0].values.sharedLimit='unknown'; assert.equal(cp(d,'CP-LIMIT-m³/h').value,null) })
console.log(`全厂分析：${count} 项独立检查通过`)
