<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, ref, watch } from 'vue'
import { WxButton, WxField, WxInput, WxSelect, WxTableSurface } from '../../components/waterx'
import MetricEditor from './MetricEditor.vue'
import DiagnosisBoards from './DiagnosisBoards.vue'
import { type ProcessPage, type LegacyMetric, type DesignVersion, type ConditionVersion, type DiagnosisVersion, type ResultRow, type Cell, type Target, type Entry, type Diagnosis, type ProjectState, latest, businessToday, stateLabels, dataLabels } from './types'
import { makeCatalog, matchCondition, matchDesign, formulaDescription } from './engine'
import { clone, loadProject, emptyProject, persistProject, saveDesign, saveCondition, saveEntry, generateDiagnosis, saveDiagnosis, lockRecord, deleteEntry, sourceStamp, demoCells, readLegacy } from './adapter'
import { dailyBasis, fillDesignBlanks, fillTargetBlanks, fillCellBlanks } from './daily-input'
import { entryTable, parseEntryTable, safeSpreadsheetText } from './entry-table'
import './process-management.css'

const props=defineProps<{page:ProcessPage;siteId:string;siteName:string;actor:string;legacyMetrics:LegacyMetric[]}>()
const emit=defineEmits<{navigate:[page:ProcessPage];configure:[scope:'design'|'condition'|'entry'|'diagnosis']}>()
const metrics=computed(()=>makeCatalog(props.legacyMetrics))
const metricMeanings=computed(()=>Object.fromEntries(metrics.value.map(m=>[m.id,m.meaning])))
const state=ref<ProjectState>(emptyProject(props.siteId,props.siteName))
const error=ref(''),notice=ref(''),storageFailed=ref(false),dirty=ref(false)
const line=ref('一期生化线'),date=ref(businessToday()),keyword=ref(''),category=ref('全部'),from=ref(''),to=ref('')
const view=ref<'list'|'detail'>('list'),editing=ref(false),correction=ref(false),reason=ref('')
const designDraft=ref<DesignVersion|null>(null),conditionDraft=ref<ConditionVersion|null>(null),conditionId=ref(''),cells=ref<Record<string,Cell>>({})
const diagnosis=ref<DiagnosisVersion|null>(null),historical=ref(false),selectedRow=ref<ResultRow|null>(null),onlyProblems=ref(false),legacyOpen=ref(false)
const printing=ref(false), reportPreview=ref(false)
const entryVersionIndex=ref(-1),diagnosisVersionIndex=ref(-1),fileInput=ref<HTMLInputElement|null>(null)
const titles:Record<ProcessPage,string>={processDesign:'工艺设计标准',conditionMatrix:'工况矩阵管理',operationEntry:'运行数据填报',processAnalysis:'工艺诊断分析',processReport:'工艺分析日报'}
const actor=()=>props.actor||'当前登录用户'
const revision=()=>({version:0,at:new Date().toISOString(),by:actor(),reason:reason.value})
const currentEntry=computed(()=>state.value.entries.find(e=>e.line===line.value&&e.date===date.value))
const currentDiagnosis=computed(()=>state.value.diagnoses.find(d=>d.line===line.value&&d.date===date.value))
const designValues=computed(()=>designDraft.value?.lines[line.value]||matchDesign(state.value,date.value)?.lines[line.value]||{})
const currentCondition=computed(()=>matchCondition(state.value,line.value,date.value))
const conditionList=computed(()=>state.value.conditions.filter(c=>latest(c.versions).line===line.value))
const categories=computed(()=>['全部',...new Set(metrics.value.map(m=>m.category))])
const editorMode=computed(() => props.page==='processDesign'?'design':props.page==='conditionMatrix'?'condition':'entry')
const editableMetrics=computed(()=>metrics.value.filter(m=>{
  const eligible=props.page==='processDesign'?m.scopes.includes('design')&&m.source!=='CALCULATED':props.page==='conditionMatrix'?m.scopes.includes('diagnosis')&&m.source!=='DESIGN':m.source==='MANUAL'
  return eligible&&m.scopes.length>0&&(category.value==='全部'||m.category===category.value)&&(!keyword.value||`${m.name} ${m.code}`.toLowerCase().includes(keyword.value.toLowerCase()))
}))
const resultRows=computed(()=>diagnosis.value?.rows.filter(r=>printing.value||reportPreview.value||((category.value==='全部'||r.category===category.value)&&(!keyword.value||`${r.name} ${r.code}`.toLowerCase().includes(keyword.value.toLowerCase()))&&(!onlyProblems.value||['warning','alarm','pending'].includes(r.state))))||[])
const entryList=computed(()=>state.value.entries.filter(e=>e.line===line.value&&(!from.value||e.date>=from.value)&&(!to.value||e.date<=to.value)).sort((a,b)=>b.date.localeCompare(a.date)))
const diagnosisList=computed(()=>state.value.diagnoses.filter(e=>e.line===line.value&&(!from.value||e.date>=from.value)&&(!to.value||e.date<=to.value)).sort((a,b)=>b.date.localeCompare(a.date)))
const stale=computed(()=>diagnosis.value&&diagnosis.value.sourceStamp!==sourceStamp(state.value,metrics.value,line.value,date.value))
const isDiagnosis=computed(()=>props.page==='processAnalysis'||props.page==='processReport')
const summaryCounts=computed(()=>['normal','warning','alarm','pending'].map(s=>({key:s,label:stateLabels[s as keyof typeof stateLabels],count:diagnosis.value?.rows.filter(r=>r.state===s).length||0})))
const legacy=computed(()=>readLegacy())
const legacyEntries=computed(()=>Array.isArray(legacy.value['waterx-operation-entry-records'])?legacy.value['waterx-operation-entry-records'] as Array<{id:string;siteId?:string;siteName?:string;line:string;entryDate:string;status:string;values:Record<string,string>}>:[])
const confirmMessage=ref('');let confirmResolve:((answer:boolean)=>void)|null=null
function ask(message:string):Promise<boolean>{confirmMessage.value=message;return new Promise(resolve=>{confirmResolve=resolve})}
function answerConfirm(answer:boolean){confirmMessage.value='';confirmResolve?.(answer);confirmResolve=null}
const busy=ref(false)
async function run(action:()=>void|Promise<void>){if(busy.value)return;busy.value=true;error.value='';try{if(storageFailed.value)throw new Error('当前档案读取失败，已阻止覆盖写入');await action()}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
function commit(next:ProjectState){state.value=persistProject(next);dirty.value=false;dropDraft();notice.value='已保存到本浏览器的项目档案';}
function reload(){try{state.value=loadProject(props.siteId,props.siteName);storageFailed.value=false}catch(e){storageFailed.value=true;error.value=(e as Error).message}}
function resetView(){reportPreview.value=false;if(!storageFailed.value)error.value='';notice.value='';view.value=props.page==='processDesign'?'detail':'list';editing.value=false;dirty.value=false;correction.value=false;reason.value='';keyword.value='';category.value='全部';diagnosis.value=null;designDraft.value=null;conditionDraft.value=null;historical.value=false}
const draftKey=(site=props.siteId,page:ProcessPage=props.page)=>`waterx-process-draft:${encodeURIComponent(site)}:${page}`
function dropDraft(){sessionStorage.removeItem(draftKey())}
function stashDraft(site=props.siteId,page:ProcessPage=props.page){if(!dirty.value||!site)return;try{sessionStorage.setItem(draftKey(site,page),JSON.stringify({line:line.value,date:date.value,designDraft:designDraft.value,conditionDraft:conditionDraft.value,conditionId:conditionId.value,cells:cells.value,diagnosis:diagnosis.value,reason:reason.value,correction:correction.value,baseRevision:state.value.revision}))}catch{notice.value='草稿暂存失败，请及时保存或导出'}}
function restoreDraft(){const raw=sessionStorage.getItem(draftKey());if(!raw)return;try{const d=JSON.parse(raw);if(d.baseRevision!==state.value.revision){notice.value='存在基于旧来源的暂存草稿，已保留；请先核查最新档案后再操作';return}line.value=d.line;date.value=d.date;designDraft.value=d.designDraft;conditionDraft.value=d.conditionDraft;conditionId.value=d.conditionId;cells.value=d.cells;diagnosis.value=d.diagnosis;reason.value=d.reason;correction.value=d.correction;view.value='detail';editing.value=!isDiagnosis.value;historical.value=false;dirty.value=true;notice.value='已恢复本窗口未保存草稿，正式档案尚未更新'}catch{notice.value='暂存草稿无法恢复，原始草稿已保留'}}
watch(()=>[props.siteId,props.page] as const,(_,previous)=>{if(previous)stashDraft(previous[0],previous[1]);reload();resetView();if(props.page==='processDesign')openDesign(false);restoreDraft()},{immediate:true})
watch([designDraft,conditionDraft,cells,diagnosis,reason,dirty],()=>stashDraft(),{deep:true})
onBeforeUnmount(()=>stashDraft())
watch(line,()=>{resetView();if(props.page==='processDesign')openDesign(false)},{flush:'sync'})
async function navigate(page:ProcessPage){if(dirty.value&&!await ask('当前修改尚未保存，确认离开？'))return;emit('navigate',page)}
async function back(){if(dirty.value&&!await ask('放弃当前未保存修改？'))return;dropDraft();resetView()}
function openDesign(edit:boolean){designDraft.value=state.value.designs.length?clone(latest(state.value.designs)):{...revision(),effective:date.value,reference:'',lines:{},demo:false};editing.value=edit;view.value='detail';reason.value='';dirty.value=false}
function designChanged(id:string,value:string){if(!designDraft.value)return;designDraft.value.lines[line.value]??={};designDraft.value.lines[line.value]![id]=value;dirty.value=true}
function saveDesignDraft(){run(()=>{if(!designDraft.value)return;commit(saveDesign(state.value,{...clone(designDraft.value),...revision()}));openDesign(false)})}
function openCondition(id?:string,copy=false){const found=state.value.conditions.find(c=>c.id===id);conditionId.value=copy||!found?crypto.randomUUID():found.id;conditionDraft.value=found?clone(latest(found.versions)):{...revision(),name:'',line:line.value,from:date.value,to:`${date.value.slice(0,4)}-12-31`,status:'DRAFT',description:'',targets:{},demo:false};if(copy){conditionDraft.value.name+='（副本）';conditionDraft.value.status='DRAFT'};editing.value=!found||copy;view.value='detail';reason.value='';dirty.value=false}
function saveConditionDraft(){run(()=>{if(!conditionDraft.value)return;commit(saveCondition(state.value,conditionId.value,{...clone(conditionDraft.value),...revision()}));openCondition(conditionId.value)})}
function setTarget(id:string,t:Target){if(conditionDraft.value){conditionDraft.value.targets[id]=t;dirty.value=true}}
function openEntry(entry?:Entry,correct=false){if(entry){date.value=entry.date;entryVersionIndex.value=entry.versions.length-1;cells.value=clone(latest(entry.versions).cells)}else{entryVersionIndex.value=-1;cells.value={}};view.value='detail';editing.value=!entry;correction.value=correct;reason.value='';dirty.value=false;historical.value=false}
function entryHistory(){const v=currentEntry.value?.versions[entryVersionIndex.value];if(v){cells.value=clone(v.cells);editing.value=false;historical.value=entryVersionIndex.value!==currentEntry.value!.versions.length-1}}
function setCell(id:string,c:Cell){cells.value[id]=c;dirty.value=true}
function editEntry(){if(currentEntry.value?.locked){correction.value=true;notice.value='已进入更正草稿。原锁定版本保留，保存时须填写原因。'}editing.value=true;historical.value=false}
function saveEntryDraft(){run(async()=>{if(currentEntry.value&&!await ask('当天已有日数据，确认保存新版本？历史版本会保留。'))return;const next=saveEntry(state.value,line.value,date.value,{...revision(),cells:clone(cells.value),demo:Object.values(cells.value).some(c=>c.source==='DEMO')},correction.value);commit(next);openEntry(currentEntry.value)})}
function deleteDaily(entry:Entry){run(async()=>{if(await ask(`删除 ${entry.date} 未锁定日数据及其本地修订？`))commit(deleteEntry(state.value,entry.id))})}
function lock(type:'entry'|'diagnosis',id:string){run(async()=>{if(await ask('锁定后须填写更正原因才能修改，确认锁定？'))commit(lockRecord(state.value,type,id,actor()))})}
function openDiagnosis(record?:Diagnosis){historical.value=false;editing.value=false;correction.value=false;reason.value='';dirty.value=false;view.value='detail';if(record){date.value=record.date;diagnosisVersionIndex.value=record.versions.length-1;diagnosis.value=clone(latest(record.versions));historical.value=true}else{diagnosisVersionIndex.value=-1;diagnosis.value=null}}
function diagnosisHistory(){const v=currentDiagnosis.value?.versions[diagnosisVersionIndex.value];if(v){diagnosis.value=clone(v);historical.value=true;dirty.value=false}}
function refreshDiagnosis(){run(()=>{if(currentDiagnosis.value?.locked&&!correction.value)throw new Error('当前结果已锁定，请先点击“更正结果”');diagnosis.value=generateDiagnosis(state.value,metrics.value,line.value,date.value,actor());historical.value=false;dirty.value=true;notice.value='已重新读取当前已保存来源并完成计算；尚未保存日报'})}
function correctDiagnosis(){correction.value=true;historical.value=false;notice.value='更正须填写原因；旧锁定版本仍保留';refreshDiagnosis()}
function saveDiagnosisDraft(){run(async()=>{if(!diagnosis.value)return;if(currentDiagnosis.value&&!await ask('当天已有诊断结果，确认更新？旧版本将保留，列表仍只有一条。'))return;commit(saveDiagnosis(state.value,metrics.value,line.value,date.value,{...clone(diagnosis.value),reason:reason.value,by:actor()},correction.value));openDiagnosis(currentDiagnosis.value)})}
function demo(kind:'complete'|'missing') {run(async()=>{
  if(!await ask('仅向空白项填入示范值，保留已维护数值（包括0）、异常及不适用记录。示范参数须经项目校核后使用。确认继续？'))return
  let count=0
  if(props.page==='processDesign'&&designDraft.value){const filled=fillDesignBlanks(metrics.value,designDraft.value.lines[line.value]||{});count=filled.count;if(count){designDraft.value.lines[line.value]=filled.values;designDraft.value.demo=true;designDraft.value.reference ||= '原型项目设计样例（待项目校核）'}}
  else if(props.page==='conditionMatrix'&&conditionDraft.value){const filled=fillTargetBlanks(metrics.value,conditionDraft.value.targets);count=filled.count;if(count){conditionDraft.value.targets=filled.targets;conditionDraft.value.demo=true;conditionDraft.value.name ||= '日常运行示范工况'}}
  else if(props.page==='operationEntry'){const filled=fillCellBlanks(cells.value,demoCells(metrics.value,kind));count=filled.count;cells.value=filled.cells}
  if(count){dirty.value=true;reason.value ||= '向空白项填入示范值（待校核）'}
  notice.value=count?`已补入 ${count} 项示范值；已维护内容保留，请核查后保存。`:'没有需要补入的空白项，未改动现有内容。'
})}
function downloadJson(value:unknown,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
const entryContext=()=>({siteId:props.siteId,line:line.value,date:date.value})
async function exportTable(kind:'entry'|'diagnosis'|'catalog') {try{
  const XLSX=await import('xlsx');let rows:Record<string,unknown>[]=[]
  if(kind==='entry')rows=entryTable(metrics.value,cells.value,entryContext())
  else if(kind==='diagnosis')rows=(diagnosis.value?.rows||[]).map(r=>({'项目':props.siteName,'工艺线':line.value,'日期':date.value,'版本':diagnosis.value?.version,'样例':diagnosis.value?.demo?'是':'否','工况':diagnosis.value?.conditionName,'设计版本':diagnosis.value?.designVersion,'运行版本':diagnosis.value?.entryVersion,'规则版本':diagnosis.value?.ruleVersion,'编码':r.code,'分类':r.category,'指标':r.name,'单位':r.unit,'设计值':r.design,'目标值':r.target,'实际值':r.actual,'偏差%':r.deviation??'不可计算','数据状态':dataLabels[r.data],'业务状态':stateLabels[r.state],'解释':r.explanation,'公式':r.formula,'规则':r.rule}))
  else rows=metrics.value.map(m=>({'ID':m.id,'编码':m.code,'分类':m.category,'指标':m.name,'单位':m.unit,'来源':m.source,'填报口径':dailyBasis(m),'参与页面':m.scopes.join('、'),'公式':formulaDescription(m),'状态规则':'项目目标＋项目容差（待校核）','缺失处理':'未判定，不回退样例'}))
  const sheet=XLSX.utils.json_to_sheet(rows.map(row=>Object.fromEntries(Object.entries(row).map(([k,v])=>[k,safeSpreadsheetText(v)]))));sheet['!cols']=Object.keys(rows[0]||{}).map(()=>({wch:22}));const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,sheet,'工艺管理');XLSX.writeFile(book,`${kind==='catalog'?'工艺指标来源矩阵':kind==='entry'?'运行数据模板':'工艺分析日报'}-${date.value}.xlsx`)
}catch(e){error.value=(e as Error).message}}
async function importEntryFile(event:Event){const input=event.target as HTMLInputElement;const file=input.files?.[0];if(!file)return;try{
  const XLSX=await import('xlsx'),book=XLSX.read(await file.arrayBuffer(),{type:'array',cellFormula:true})
  const sheet=book.Sheets[book.SheetNames[0]!]
  if(!sheet)throw new Error('文件没有可读取的工作表')
  if(Object.entries(sheet).some(([key,value])=>!key.startsWith('!')&&value?.f))throw new Error('模板含表格公式，请改为一手观测值后导入')
  const rows=XLSX.utils.sheet_to_json<Record<string,unknown>>(sheet,{defval:''})
  const next=parseEntryTable(rows,metrics.value,cells.value,entryContext())
  if(Object.keys(cells.value).length&&!await ask('导入将替换表格中对应指标的当前草稿内容，其他指标和已保存历史保持不变。确认继续？'))return
  cells.value=next;dirty.value=true;notice.value=`已导入 ${rows.length} 项到草稿，请核查后保存`

}catch(e){error.value=(e as Error).message}finally{input.value=''}}
function importLegacyEntry(id:string){run(async()=>{const old=legacyEntries.value.find(e=>e.id===id);if(!old)return;if(old.siteId!==props.siteId)throw new Error('旧记录项目身份缺失或不一致，不能导入当前项目');if(currentEntry.value)throw new Error('请在空白日期导入旧记录，避免覆盖');if(!await ask(`将旧记录 ${old.entryDate} ${old.line} 复制到新草稿？原记录保持不变。`))return;line.value=old.line;date.value=old.entryDate;cells.value=Object.fromEntries(Object.entries(old.values).filter(([id])=>metrics.value.some(m=>m.id===id&&m.source==='MANUAL')).map(([id,value])=>[id,{value,state:'VALID',source:old.id.startsWith('demo-')?'DEMO':'IMPORT',note:'旧版记录导入，数据来源待复核'} as Cell]));view.value='detail';editing.value=true;dirty.value=true;reason.value='旧版日数据导入';legacyOpen.value=false})}
async function sourceLink(row:ResultRow){const snapshot=diagnosis.value;selectedRow.value=null;emit('navigate',row.source==='设计标准'?'processDesign':'operationEntry');await nextTick();if(row.source==='设计标准'){const v=state.value.designs.find(v=>v.version===snapshot?.designVersion);if(v){designDraft.value=clone(v);editing.value=false}}else{const e=state.value.entries.find(e=>e.id===snapshot?.entryId);if(e){openEntry(e);entryVersionIndex.value=e.versions.findIndex(v=>v.version===snapshot?.entryVersion);entryHistory()}}}
async function printReport(){printing.value=true;await nextTick();window.print();printing.value=false}
</script>

<template>
<section class="pm-workspace" :class="{'pm-printing':isDiagnosis&&view==='detail','pm-diagnostic-view':isDiagnosis&&view==='detail'&&!reportPreview}">
  <header class="pm-toolbar pm-no-print"><div class="pm-title"><strong>{{titles[page]}}</strong><small>{{siteName}} · 本地试用</small></div><WxField label="工艺线"><WxSelect v-model="line" :disabled="editing||dirty"><option>一期生化线</option><option>二期生化线</option></WxSelect></WxField><WxField v-if="view==='detail'&&page!=='conditionMatrix'&&page!=='processDesign'" label="业务日期"><WxInput v-model="date" type="date" :disabled="!!currentEntry||!!diagnosis||dirty||historical" /></WxField><div class="pm-actions"><WxButton v-if="view==='detail'&&page!=='processDesign'" @click="back">返回列表</WxButton><WxButton @click="legacyOpen=!legacyOpen">旧版档案</WxButton><WxButton @click="exportTable('catalog')">指标来源矩阵</WxButton><WxButton @click="downloadJson(state,'工艺项目档案备份.json')">备份档案</WxButton></div></header>
  <p v-if="isDiagnosis" class="pm-muted pm-no-print">首版仅汇总人工日数据并分析目标偏差，不生成原因诊断、操作建议或设备指令；运行目标不等同于法定限值。</p>
  <div v-if="error" role="alert" class="pm-message pm-error pm-no-print">{{error}}<button @click="error=''" aria-label="关闭错误">×</button></div><div v-if="notice" role="status" class="pm-message pm-no-print">{{notice}}<button @click="notice=''" aria-label="关闭提示">×</button></div>
  <aside v-if="legacyOpen" class="pm-panel pm-no-print"><b>旧版数据保留区</b><p>旧设计标准和工况未绑定完整项目身份；旧日报缺少完整诊断快照。原始数据保持不变，可导出核查。仅项目身份一致的运行记录可复制为新草稿。</p><WxButton @click="downloadJson(legacy,'工艺旧版档案.json')">导出全部旧版数据</WxButton><div class="pm-table-scroll"><table class="pm-table"><thead><tr><th>项目</th><th>工艺线</th><th>日期</th><th>旧状态</th><th>操作</th></tr></thead><tbody><tr v-for="e in legacyEntries" :key="e.id"><td>{{e.siteName||'未绑定'}}</td><td>{{e.line}}</td><td>{{e.entryDate}}</td><td>{{e.status}}</td><td><WxButton :disabled="page!=='operationEntry'||e.siteId!==siteId" @click="importLegacyEntry(e.id)">复制到日数据草稿</WxButton></td></tr></tbody></table></div></aside>

  <template v-if="page==='processDesign'">
    <div class="pm-section-head pm-no-print"><span>一个项目一份设计档案，按工艺线维护。当前查看 {{designDraft?.version?`V${designDraft.version}`:'未保存草稿'}}；维护时基于最新版本。</span><div class="pm-actions"><WxButton v-if="!editing" variant="primary" @click="openDesign(true)">维护设计标准</WxButton><template v-else><WxButton @click="demo('complete')">补入空白设计样例</WxButton><WxButton @click="dropDraft();openDesign(false)">取消</WxButton><WxButton variant="primary" @click="saveDesignDraft">保存设计版本</WxButton></template></div></div>
    <div v-if="designDraft" class="pm-meta pm-no-print"><WxField label="设计文件来源"><WxInput v-model="designDraft.reference" :disabled="!editing" @update:model-value="dirty=true" /></WxField><WxField label="生效日期"><WxInput v-model="designDraft.effective" type="date" :disabled="!editing" @update:model-value="dirty=true" /></WxField><WxField v-if="editing" label="修改原因"><WxInput v-model="reason" placeholder="例如：按一期竣工设计资料维护" /></WxField><span v-if="designDraft.demo" class="pm-badge">示范资料 · 待项目校核</span></div>
    <div v-if="state.designs.length&&!editing" class="pm-history pm-no-print">设计修订：<button v-for="v in state.designs" :key="v.version" @click="designDraft=clone(v)">V{{v.version}} · {{v.effective}}</button></div>
  </template>
  <template v-else-if="page==='conditionMatrix'">
    <template v-if="view==='list'"><div class="pm-section-head"><span>同一工艺线、同一日期匹配一套已启用工况。</span><WxButton variant="primary" @click="openCondition()">新建工况</WxButton></div><WxTableSurface><div class="pm-table-scroll"><table class="pm-table"><thead><tr><th>工况名称</th><th>有效日期</th><th>状态</th><th>版本</th><th>操作</th></tr></thead><tbody><tr v-for="c in conditionList" :key="c.id"><td><button class="pm-link" @click="openCondition(c.id)">{{latest(c.versions).name}}</button><small v-if="latest(c.versions).demo">示范工况</small></td><td>{{latest(c.versions).from}} 至 {{latest(c.versions).to}}</td><td>{{{DRAFT:'草稿',ACTIVE:'已启用',RETIRED:'已停用'}[latest(c.versions).status]}}</td><td>V{{latest(c.versions).version}}</td><td><WxButton @click="openCondition(c.id,true)">复制</WxButton></td></tr><tr v-if="!conditionList.length"><td colspan="5" class="pm-empty">暂无工况，请新建并维护目标值。</td></tr></tbody></table></div></WxTableSurface></template>
    <template v-else-if="conditionDraft"><div class="pm-section-head"><span>{{conditionDraft.demo?'示范目标 · ':''}}项目参数待校核；目标不等同于法定排放限值。</span><div class="pm-actions"><WxButton v-if="!editing" @click="openCondition(conditionId);editing=true">编辑 / 停用</WxButton><template v-else><WxButton @click="demo('complete')">补入空白目标样例</WxButton><WxButton variant="primary" @click="saveConditionDraft">保存工况版本</WxButton></template></div></div><div v-if="!editing" class="pm-history">工况修订：<button v-for="v in state.conditions.find(c=>c.id===conditionId)?.versions||[]" :key="v.version" :aria-pressed="conditionDraft.version===v.version" @click="conditionDraft=clone(v)">V{{v.version}} · {{v.from}} · {{v.reason}}</button><span>当前查看 V{{conditionDraft.version}}；编辑基于最新版本。</span></div><div class="pm-meta"><WxField label="工况名称"><WxInput v-model="conditionDraft.name" :disabled="!editing" @update:model-value="dirty=true" /></WxField><WxField label="开始日期"><WxInput v-model="conditionDraft.from" type="date" :disabled="!editing" @update:model-value="dirty=true" /></WxField><WxField label="结束日期"><WxInput v-model="conditionDraft.to" type="date" :disabled="!editing" @update:model-value="dirty=true" /></WxField><WxField label="状态"><WxSelect v-model="conditionDraft.status" :disabled="!editing" @update:model-value="dirty=true"><option value="DRAFT">草稿</option><option value="ACTIVE">已启用</option><option value="RETIRED">已停用</option></WxSelect></WxField><WxField label="适用说明"><WxInput v-model="conditionDraft.description" :disabled="!editing" @update:model-value="dirty=true" /></WxField><WxField v-if="editing" label="修改原因"><WxInput v-model="reason" /></WxField></div></template>
  </template>
  <template v-else-if="page==='operationEntry'">
    <template v-if="view==='list'"><div class="pm-section-head"><span>日数据 {{entryList.length}} 条 · 人工日填报，同日更新保留修订</span><div class="pm-actions"><WxField label="新建日期"><WxInput v-model="date" type="date" /></WxField><WxButton variant="primary" @click="openEntry(currentEntry)">打开 / 新建日数据</WxButton></div></div><div class="pm-filters"><WxField label="开始日期"><WxInput v-model="from" type="date" /></WxField><WxField label="结束日期"><WxInput v-model="to" type="date" /></WxField></div><WxTableSurface><div class="pm-table-scroll"><table class="pm-table"><thead><tr><th>日期</th><th>已记录值</th><th>版本 / 状态</th><th>最后保存</th><th>操作</th></tr></thead><tbody><tr v-for="e in entryList" :key="e.id"><td><button class="pm-link" @click="openEntry(e)">{{e.date}}</button><small v-if="latest(e.versions).demo">示范数据</small></td><td>{{Object.values(latest(e.versions).cells).filter(c=>c.value.trim()||c.state==='NA').length}} 项</td><td>V{{latest(e.versions).version}} · {{e.locked?'已锁定':'可修订'}}</td><td>{{latest(e.versions).by}}<small>{{new Date(latest(e.versions).at).toLocaleString('zh-CN')}}</small></td><td><div class="pm-actions"><WxButton :disabled="e.locked" @click="lock('entry',e.id)">锁定</WxButton><WxButton variant="danger" @click="deleteDaily(e)">删除</WxButton></div></td></tr><tr v-if="!entryList.length"><td colspan="5" class="pm-empty">暂无日数据。选择日期后新建，支持人工填报及模板导入。</td></tr></tbody></table></div></WxTableSurface></template>
    <template v-else><div class="pm-section-head"><span>匹配工况：{{currentCondition?.value.name||'未匹配'}} · {{editing?'编辑草稿':historical?'历史版本（只读）':'已保存'}}</span><div class="pm-actions"><WxButton @click="exportTable('entry')">导出数据 / 模板</WxButton><WxButton v-if="!editing&&!historical" @click="editEntry">{{currentEntry?.locked?'更正日数据':'编辑日数据'}}</WxButton><template v-if="editing"><WxButton @click="fileInput?.click()">导入模板</WxButton><WxButton @click="demo('complete')">补入完整样例</WxButton><WxButton @click="demo('missing')">补入缺失样例</WxButton><WxButton variant="primary" @click="saveEntryDraft">保存日数据</WxButton></template></div></div><input ref="fileInput" class="pm-file" type="file" accept=".xlsx,.xls" @change="importEntryFile" /><div class="pm-meta"><WxField v-if="editing" label="更新 / 更正原因"><WxInput v-model="reason" /></WxField><WxField v-if="currentEntry&&!editing" label="查看版本"><WxSelect :model-value="String(entryVersionIndex)" @update:model-value="entryVersionIndex=Number($event);entryHistory()"><option v-for="(v,i) in currentEntry.versions" :key="v.version" :value="i">V{{v.version}} · {{v.reason||'首次保存'}}</option></WxSelect></WxField><WxButton v-if="currentEntry&&!editing" @click="navigate('processAnalysis')">进入工艺诊断</WxButton></div></template>
  </template>
  <template v-else>
    <template v-if="view==='list'"><div class="pm-section-head pm-no-print"><span>{{page==='processReport'?'日报直接引用已保存诊断版本':'每天一份正式结果，更新时保留历史版本'}} · {{diagnosisList.length}} 条</span><div v-if="page==='processAnalysis'" class="pm-actions"><WxField label="分析日期"><WxInput v-model="date" type="date" /></WxField><WxButton variant="primary" @click="openDiagnosis(currentDiagnosis)">打开 / 生成诊断</WxButton></div></div><div class="pm-filters pm-no-print"><WxField label="开始日期"><WxInput v-model="from" type="date" /></WxField><WxField label="结束日期"><WxInput v-model="to" type="date" /></WxField></div><WxTableSurface><div class="pm-table-scroll"><table class="pm-table"><thead><tr><th>分析日期</th><th>匹配工况</th><th>数据有效 / 总项数</th><th>预警 / 告警 / 未判定</th><th>状态 / 版本</th><th>操作</th></tr></thead><tbody><tr v-for="d in diagnosisList" :key="d.id"><td><button class="pm-link" @click="openDiagnosis(d)">{{d.date}}</button><small v-if="latest(d.versions).demo">含示范数据</small></td><td>{{latest(d.versions).conditionName}}</td><td>{{latest(d.versions).rows.filter(r=>r.data==='VALID').length}} / {{latest(d.versions).rows.length}}</td><td>{{latest(d.versions).rows.filter(r=>r.state==='warning').length}} / {{latest(d.versions).rows.filter(r=>r.state==='alarm').length}} / {{latest(d.versions).rows.filter(r=>r.state==='pending').length}}</td><td>{{d.locked?'已锁定':'已保存'}} · V{{latest(d.versions).version}}</td><td><WxButton :disabled="d.locked" @click="lock('diagnosis',d.id)">锁定</WxButton></td></tr><tr v-if="!diagnosisList.length"><td colspan="6" class="pm-empty">暂无已保存结果。请完成设计标准、有效工况和当天日数据后生成诊断。</td></tr></tbody></table></div></WxTableSurface></template>
    <template v-else><div class="pm-section-head pm-no-print"><div><b>{{historical?'已保存快照':diagnosis?'诊断草稿':'待生成诊断'}}</b><small v-if="diagnosis">{{diagnosis.conditionName}} · 设计 V{{diagnosis.designVersion??'未匹配'}} · 运行 V{{diagnosis.entryVersion??'未保存'}} · {{diagnosis.ruleVersion}}</small></div><div class="pm-actions"><template v-if="page==='processAnalysis'"><WxButton v-if="currentDiagnosis?.locked" @click="correctDiagnosis">更正结果</WxButton><WxButton :disabled="!!currentDiagnosis?.locked&&!correction" @click="refreshDiagnosis">更新诊断</WxButton><WxButton variant="primary" :disabled="!diagnosis||historical||!!stale" @click="saveDiagnosisDraft">保存日报</WxButton></template><WxButton :disabled="!historical" @click="exportTable('diagnosis')">导出日报</WxButton><WxButton :disabled="!historical" @click="reportPreview=!reportPreview">{{reportPreview?'返回分析看板':'预览 / 打印日报'}}</WxButton></div></div>
      <p v-if="stale" class="pm-message pm-no-print">{{historical?'来源或规则已有新版本；这里仍保留当时的结果。需要最新结论时，请在工艺诊断中更新并另存修订。':'来源已更新，当前草稿已过期，请重新更新诊断。'}}</p><div class="pm-meta pm-no-print"><WxField v-if="!historical" label="更新 / 更正原因"><WxInput v-model="reason" /></WxField><WxField v-if="currentDiagnosis&&historical" label="历史版本"><WxSelect :model-value="String(diagnosisVersionIndex)" @update:model-value="diagnosisVersionIndex=Number($event);diagnosisHistory()"><option v-for="(v,i) in currentDiagnosis.versions" :key="v.version" :value="i">V{{v.version}} · {{v.reason||'首次保存'}}</option></WxSelect></WxField></div>
      <div v-if="diagnosis" class="pm-summary"><span v-for="c in summaryCounts" :key="c.key" :class="c.key">{{c.label}} <b>{{c.count}}</b></span><span v-if="diagnosis.demo" class="pm-badge">含示范数据</span><small>{{diagnosis.summary}}</small></div>
      <div v-if="reportPreview" class="pm-section-head pm-no-print"><span>已保存版本完整日报 · 不受查找及异常筛选影响 · A4横版打印样式</span><WxButton @click="printReport">系统打印 / 另存PDF</WxButton></div><div class="pm-print-title" :class="{'pm-report-heading':reportPreview}" v-if="diagnosis"><h1>工艺分析日报</h1><p>{{siteName}} · {{line}} · {{date}} · V{{diagnosis.version}}</p><p>{{diagnosis.conditionName}} · {{diagnosis.by}} · {{new Date(diagnosis.at).toLocaleString('zh-CN')}} · {{diagnosis.ruleVersion}}</p></div>
    </template>
  </template>

  <template v-if="view==='detail'"><div class="pm-filters pm-no-print"><WxField v-if="!isDiagnosis" label="指标分类"><WxSelect v-model="category"><option v-for="c in categories" :key="c">{{c}}</option></WxSelect></WxField><WxField label="查找指标"><WxInput v-model="keyword" placeholder="名称或编码" /></WxField><label v-if="isDiagnosis" class="pm-checkbox"><input v-model="onlyProblems" type="checkbox" />仅看异常 / 未判定</label><WxButton v-if="!isDiagnosis||!diagnosis||reportPreview" @click="emit('configure',page==='processDesign'?'design':page==='conditionMatrix'?'condition':page==='operationEntry'?'entry':'diagnosis')">配置指标</WxButton><span class="pm-muted">{{dirty?'有未保存修改':'项目参数待校核'}}</span></div>
    <WxTableSurface v-if="!isDiagnosis"><MetricEditor :metrics="editableMetrics" :mode="editorMode" :values="designValues" :targets="conditionDraft?.targets||{}" :cells="cells" :editable="editing" @design="designChanged" @target="setTarget" @cell="setCell" /></WxTableSurface>
    <DiagnosisBoards v-else-if="diagnosis&&!reportPreview" :rows="resultRows" :meanings="metricMeanings" @detail="selectedRow=$event" @configure="emit('configure','diagnosis')" />
    <WxTableSurface v-if="isDiagnosis&&diagnosis" class="pm-report-print-table" :class="{'pm-report-preview':reportPreview}"><div class="pm-table-scroll pm-results"><table class="pm-table"><colgroup><col style="width:18%"><col style="width:7%"><col style="width:10%"><col style="width:10%"><col style="width:10%"><col style="width:14%"><col style="width:15%"><col style="width:16%"></colgroup><thead><tr><th>指标</th><th>单位</th><th>设计值</th><th>目标值</th><th>实际值</th><th>偏差 / 状态</th><th>数据状态</th><th>结果解读</th></tr></thead><tbody><tr v-for="r in resultRows" :key="r.id"><td><b>{{r.name}}</b><small>{{r.category}} · {{r.code}}</small></td><td>{{r.unit}}</td><td>{{r.design}}</td><td>{{r.target}}</td><td><strong>{{r.actual||'未取得'}}</strong></td><td :class="r.state"><b>{{stateLabels[r.state]}}</b><small>{{r.deviation!==null?`${r.deviation>0?'+':''}${r.deviation.toFixed(1)}%`:r.difference!==null?`差值 ${r.difference}`:'不计算偏差'}}</small></td><td>{{dataLabels[r.data]}}<small>{{r.source}}</small></td><td><button class="pm-link pm-no-print" @click="selectedRow=r">规则 / 来源 / 解读</button><span :class="reportPreview?'':'pm-print-only'">{{r.explanation}}</span></td></tr><tr v-if="!resultRows.length"><td colspan="8" class="pm-empty">没有符合条件的指标。</td></tr></tbody></table></div></WxTableSurface>
    <div v-if="isDiagnosis&&!diagnosis" class="pm-empty pm-panel">点击“更新诊断”，从已保存来源生成本日结果。</div>
  </template>
  <div v-if="selectedRow" class="pm-overlay pm-no-print" @click.self="selectedRow=null"><section class="pm-dialog" role="dialog" aria-modal="true" aria-label="指标规则与结果解读"><header><strong>{{selectedRow.name}}</strong><WxButton @click="selectedRow=null">关闭</WxButton></header><dl><dt>指标编码 / 单位</dt><dd>{{selectedRow.code}} / {{selectedRow.unit}}</dd><dt>数据来源与状态</dt><dd>{{selectedRow.source}} · {{dataLabels[selectedRow.data]}}</dd><dt>计算公式</dt><dd>{{selectedRow.formula||'直接引用已保存原始值'}}</dd><dt>判定规则</dt><dd>{{selectedRow.rule}}</dd><dt>结果解读</dt><dd>{{selectedRow.explanation||'缺少可用数据，暂不形成结论'}}</dd><dt>版本依据</dt><dd>设计 V{{diagnosis?.designVersion}} / 工况 V{{diagnosis?.conditionVersion}} / 运行 V{{diagnosis?.entryVersion}} / {{diagnosis?.ruleVersion}}</dd></dl><WxButton @click="sourceLink(selectedRow)">查看来源模块</WxButton></section></div>
  <div v-if="confirmMessage" class="pm-overlay pm-no-print"><section class="pm-dialog" role="alertdialog" aria-modal="true" aria-label="确认操作"><header><strong>确认操作</strong></header><p>{{confirmMessage}}</p><div class="pm-actions"><WxButton @click="answerConfirm(false)">取消操作</WxButton><WxButton variant="primary" @click="answerConfirm(true)">确认继续</WxButton></div></section></div>
</section>
</template>
