import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import { createRequire } from 'node:module'
import { fileURLToPath } from 'node:url'
const require=createRequire(import.meta.url), ts=require('typescript'), Module=require('node:module')
const dir=path.dirname(fileURLToPath(import.meta.url)),cache=new Map()
function load(name){const file=path.resolve(dir,name+'.ts');if(cache.has(file))return cache.get(file).exports;const m=new Module(file);m.filename=file;m.paths=Module._nodeModulePaths(dir);m.require=(id)=>id.startsWith('.')?load(id):require(id);cache.set(file,m);m._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,file);return m.exports}
const engine=load('./engine'),a=load('./adapter'),types=load('./types')
let cases=0;function test(name,fn){fn();cases++;console.log(`PASS ${name}`)}
const raw=(category,name,unit='mg/L',formula='')=>({code:name,category,name,unit,formula,design:'',target:'10',actual:'999',meaning:'',scopes:['design','condition','entry','diagnosis']})
const metrics=engine.makeCatalog([raw('进水水质','COD'),raw('出水水质','COD'),raw('处理效能','COD去除率','%','formula'),raw('水量控制','日进水量','万m³/d'),raw('水量控制','设计处理水量','万m³/d'),raw('水量控制','厌氧段有效池容','万m³'),raw('水量控制','厌氧段HRT','h','formula'),raw('曝气控制','日曝气量','万Nm³'),raw('曝气控制','当前气水比','—','formula'),raw('加药控制','碳源投加量','t/d'),raw('加药控制','除磷药剂量','t/d'),raw('加药控制','吨水药耗','kg/m³','formula'),raw('污泥性状','SRT','d','unconfirmed')])
const cell=value=>({value:String(value),source:'MANUAL',state:'VALID',note:''}), target=(value,mode='POINT')=>({value:String(value),mode,warning:10,alarm:50})
const cells={'进水水质::COD':cell(100),'出水水质::COD':cell(20),'水量控制::日进水量':cell(7),'曝气控制::日曝气量':cell(15.8),'加药控制::碳源投加量':cell(3),'加药控制::除磷药剂量':cell(1)}
const designs={'水量控制::厌氧段有效池容':'0.7','水量控制::设计处理水量':'7'},targets=Object.fromEntries(metrics.map(m=>[m.id,target(10)]))
const rows=()=>engine.calculateRows(metrics,designs,targets,cells),get=(r,id)=>r.find(x=>x.id===id)
test('完整数值、真实0、科学计数与限定符',()=>{assert.equal(engine.numeric('0'),0);assert.equal(engine.numeric(''),null);assert.equal(engine.numeric('<0.02'),null);assert.equal(engine.numeric('13foo'),null);assert.equal(engine.numeric('8.6×10⁶'),8600000);assert.equal(engine.numeric('10⁷'),10000000)})
test('缺失不退回999样例',()=>{const r=engine.calculateRows(metrics,{},targets,{});assert.ok(r.every(x=>x.state==='pending'));assert.equal(get(r,'进水水质::COD').actual,'')})
test('去除率由进出水实测值生成',()=>assert.equal(get(rows(),'处理效能::COD去除率').actual,'80'))
test('HRT日转小时正确',()=>assert.equal(get(rows(),'水量控制::厌氧段HRT').actual,'2.4'))
test('气水比使用同日日累计气量，不推算瞬时风量',()=>assert.equal(get(rows(),'曝气控制::当前气水比').actual,'2.2571'))
test('商品药耗吨转千克并换算水量',()=>assert.equal(get(rows(),'加药控制::吨水药耗').actual,'0.0571'))
test('复杂模型不使用旧样例结果',()=>assert.equal(get(rows(),'污泥性状::SRT').data,'UNCONFIGURED'))
test('除0与缺失依赖不生成正常',()=>{const r=engine.calculateRows(metrics,designs,targets,{...cells,'进水水质::COD':cell(0)});assert.equal(get(r,'处理效能::COD去除率').data,'CALC_INVALID')})
test('零目标使用绝对差值',()=>{const r=engine.calculateRows(metrics,designs,{'进水水质::COD':target(0)},cells)[0];assert.equal(r.deviation,null);assert.equal(r.state,'warning')})
test('上限低于目标不报警',()=>assert.equal(engine.calculateRows(metrics,designs,{'进水水质::COD':target(120,'UPPER')},cells)[0].state,'normal'))
test('下限高于目标不报警',()=>assert.equal(engine.calculateRows(metrics,designs,{'进水水质::COD':target(90,'LOWER')},cells)[0].state,'normal'))
test('区间与非法区间',()=>{assert.equal(engine.calculateRows(metrics,designs,{'进水水质::COD':target('90～110','RANGE')},cells)[0].state,'normal');assert.ok(engine.targetError(target('120～80','RANGE')))})
test('无工况与无目标保持未判定',()=>assert.ok(engine.calculateRows(metrics,designs,undefined,cells).every(r=>r.state==='pending')))
test('不适用和异常有独立状态',()=>{assert.equal(engine.calculateRows(metrics,designs,targets,{'进水水质::COD':{...cell(1),state:'NA',note:'无该工艺'}})[0].data,'NA');assert.equal(engine.calculateRows(metrics,designs,targets,{'进水水质::COD':{...cell(1),state:'INVALID'}})[0].data,'INVALID')})
const revision={version:1,at:'2026-09-05T00:00:00Z',by:'验收用户',reason:'验收'},line='一期生化线',date='2026-09-05'
let state=a.emptyProject('site-A','验收水厂')
state=a.saveDesign(state,{...revision,effective:'2026-01-01',reference:'验收设计',lines:{[line]:designs},demo:true})
const condition={...revision,name:'日常工况',line,from:'2026-01-01',to:'2026-12-31',status:'ACTIVE',description:'',targets,demo:true}
state=a.saveCondition(state,'condition-1',condition)
state=a.saveEntry(state,line,date,{...revision,cells,demo:true})
test('有效工况重叠拦截但另一工艺线允许',()=>{assert.throws(()=>a.saveCondition(state,'c2',condition),/重叠/);assert.doesNotThrow(()=>a.saveCondition(state,'c2',{...condition,line:'二期生化线'}))})
test('草稿工况不参与匹配',()=>assert.equal(engine.matchCondition({...state,conditions:[{id:'d',versions:[{...condition,status:'DRAFT'}]}]},line,date),undefined))
test('生成但不改变源数据',()=>{const before=JSON.stringify(state);a.generateDiagnosis(state,metrics,line,date,'验收');assert.equal(JSON.stringify(state),before)})
state=a.saveDiagnosis(state,metrics,line,date,a.generateDiagnosis(state,metrics,line,date,'验收'))
test('同日保存仍一行且版本保留',()=>{state=a.saveDiagnosis(state,metrics,line,date,{...a.generateDiagnosis(state,metrics,line,date,'验收'),reason:'再次保存'});assert.equal(state.diagnoses.length,1);assert.equal(state.diagnoses[0].versions.length,2)})
test('修改来源后必须重新生成',()=>{const d=a.generateDiagnosis(state,metrics,line,date,'验收');state=a.saveEntry(state,line,date,{...revision,cells:{...cells,'出水水质::COD':cell(10)},demo:true});assert.throws(()=>a.saveDiagnosis(state,metrics,line,date,{...d,reason:'过期'}),/来源已变化/)})
test('锁定后禁止直接覆盖；更正保留旧版本',()=>{state=a.lockRecord(state,'diagnosis',state.diagnoses[0].id);const d={...a.generateDiagnosis(state,metrics,line,date,'验收'),reason:'更正'};assert.throws(()=>a.saveDiagnosis(state,metrics,line,date,d),/锁定/);state=a.saveDiagnosis(state,metrics,line,date,d,true);assert.equal(state.diagnoses[0].versions.length,3);assert.equal(get(state.diagnoses[0].versions[0].rows,'出水水质::COD').actual,'20')})
test('已引用日数据不可删除',()=>assert.throws(()=>a.deleteEntry(state,state.entries[0].id),/不可删除/))
test('新设计和工况不会改写历史快照',()=>{const old=JSON.stringify(state.diagnoses);state=a.saveDesign(state,{...state.designs[0],lines:{[line]:{'水量控制::厌氧段有效池容':'7'}}});state=a.saveCondition(state,'condition-1',{...condition,targets:{'进水水质::COD':target(200)}});assert.equal(JSON.stringify(state.diagnoses),old)})
test('未来设计不提前生效',()=>{state=a.saveDesign(state,{...state.designs[0],effective:'2027-01-01'});assert.notEqual(engine.matchDesign(state,date).version,3)})
test('跨项目隔离、并发写冲突与原子保存',()=>{const map=new Map(),store={getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v)};const stale=structuredClone(state);state=a.persistProject(state,store);assert.throws(()=>a.persistProject(stale,store),/其他窗口/);assert.equal(a.loadProject('site-B','B',store).entries.length,0);assert.equal(a.loadProject('site-A','A',store).diagnoses.length,1)})
test('无有效来源不能保存正式日报',()=>{const s=a.emptyProject('site-B','B');assert.throws(()=>a.saveDiagnosis(s,metrics,line,date,a.generateDiagnosis(s,metrics,line,date,'验收')),/缺少/)})
test('另一工艺线未维护设计不能借用项目版本',()=>{const other='二期生化线';let s=a.saveCondition(state,'other',{...condition,line:other});s=a.saveEntry(s,other,date,{...revision,cells,demo:true});const result=a.generateDiagnosis(s,metrics,other,date,'验收');assert.equal(result.designVersion,null);assert.throws(()=>a.saveDiagnosis(s,metrics,other,date,result),/缺少/)})
test('非正设计池容不参与HRT计算',()=>{for(const value of ['-1','0'])assert.equal(get(engine.calculateRows(metrics,{...designs,'水量控制::厌氧段有效池容':value},targets,cells),'水量控制::厌氧段HRT').data,'CALC_INVALID')})
test('不适用或异常必须有原因',()=>{for(const status of ['NA','INVALID'])assert.throws(()=>a.saveEntry(state,line,date,{...revision,cells:{'进水水质::COD':{...cell(0),state:status,note:''}},demo:false}),/原因/)})
test('锁定日数据须更正并保留原值',()=>{const s=a.lockRecord(state,'entry',state.entries[0].id,'验收');assert.throws(()=>a.saveEntry(s,line,date,{...revision,cells,demo:true}),/锁定/);const next=a.saveEntry(s,line,date,{...revision,cells,demo:true},true);assert.equal(next.entries[0].versions.length,s.entries[0].versions.length+1);assert.deepEqual(next.entries[0].versions[0],s.entries[0].versions[0]);assert.equal(s.events.at(-1).by,'验收')})
test('来源规则版本改变使旧草稿失效',()=>{const result=a.generateDiagnosis(state,metrics,line,date,'验收');result.sourceStamp+='旧';assert.throws(()=>a.saveDiagnosis(state,metrics,line,date,result),/来源已变化/)})
test('存储失败不修改调用者与旧记录',()=>{const before=JSON.stringify(state),store={getItem:()=>JSON.stringify(state),setItem:()=>{throw Error('配额已满')}};assert.throws(()=>a.persistProject(state,store),/配额已满/);assert.equal(JSON.stringify(state),before)})
test('损坏档案读取失败不写入覆盖',()=>{let writes=0;assert.throws(()=>a.loadProject('site-A','A',{getItem:()=>'{broken',setItem:()=>writes++}));assert.equal(writes,0)})
test('固定演示数据一次形成完整且可追溯的日分析链',()=>{const demoMetrics=metrics.map(m=>({...m,design:m.source==='CALCULATED'?'':'100'}));const demo=a.fixedDemoProject('demo-site','演示水厂',demoMetrics,'演示用户');assert.equal(demo.designs.length,1);assert.equal(demo.conditions.length,1);assert.equal(demo.entries.length,1);assert.equal(demo.diagnoses.length,1);assert.equal(demo.entries[0].date,a.FIXED_DEMO_DATE);assert.equal(demo.conditions[0].versions[0].status,'ACTIVE');assert.ok(demo.entries[0].versions[0].demo);assert.ok(demo.diagnoses[0].versions[0].demo);assert.equal(demo.diagnoses[0].versions[0].entryId,demo.entries[0].id);assert.equal(demo.diagnoses[0].versions[0].conditionId,demo.conditions[0].id)})
const daily=load('./daily-input'),table=load('./entry-table'),XLSX=require('xlsx')
test('日累计、日均与计算口径分离',()=>{assert.equal(daily.dailyBasis(metrics.find(m=>m.name==='日进水量')),'日累计');assert.equal(daily.dailyBasis(metrics.find(m=>m.name==='日曝气量')),'日累计');assert.equal(daily.dailyBasis(metrics[0]),'日均值');assert.equal(daily.dailyBasis(metrics[2]),'同日日数据计算')})
test('修改控制方式的空目标不注入示例数字',()=>assert.equal(daily.emptyTarget(metrics[0]).value,''))
test('设计样例只补空白，保留0及已维护来源值',()=>{const input={'进水水质::COD':'0','出水水质::COD':'42'};const filled=daily.fillDesignBlanks(metrics.map(m=>({...m,design:'99'})),input);assert.equal(filled.values['进水水质::COD'],'0');assert.equal(filled.values['出水水质::COD'],'42');assert.ok(filled.count>0);assert.equal(Object.keys(input).length,2)})
test('目标样例保留现有值、控制方式与零容差',()=>{const input={'进水水质::COD':{...target(0),warning:0},'出水水质::COD':{value:'',mode:'LOWER',warning:0,alarm:1}};const f=daily.fillTargetBlanks(metrics,input);assert.deepEqual(f.targets['进水水质::COD'],input['进水水质::COD']);assert.deepEqual(f.targets['出水水质::COD'],{value:'10',mode:'LOWER',warning:0,alarm:1});assert.equal(input['出水水质::COD'].value,'')})
test('日数据样例不覆盖0、异常、不适用或已写说明',()=>{const input={a:cell(0),b:{...cell(''),state:'INVALID',note:'异常'},c:{...cell(''),state:'NA',note:'不适用'},d:{...cell(''),note:'待核实'}};const f=daily.fillCellBlanks(input,{a:cell(99),b:cell(99),c:cell(99),d:cell(99),e:cell(2)});assert.equal(f.count,1);assert.deepEqual(f.cells.a,input.a);assert.deepEqual(f.cells.b,input.b);assert.deepEqual(f.cells.c,input.c);assert.deepEqual(f.cells.d,input.d);assert.equal(input.e,undefined)})
const context={siteId:'site-A',line,date}
test('真实xlsx导出再读取：0、负值、检出限限定符和口径保真',()=>{const values={...cells,'进水水质::COD':cell(0),'出水水质::COD':{...cell('<0.02'),note:'限定符保留'},'水量控制::日进水量':cell(-1)};const rows=table.entryTable(metrics,values,context);const sheet=XLSX.utils.json_to_sheet(rows.map(r=>Object.fromEntries(Object.entries(r).map(([k,v])=>[k,table.safeSpreadsheetText(v)]))));const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,sheet,'日数据');const decoded=XLSX.read(XLSX.write(book,{type:'buffer',bookType:'xlsx'}),{type:'buffer'});const parsed=table.parseEntryTable(XLSX.utils.sheet_to_json(decoded.Sheets['日数据'],{defval:''}),metrics,{},context);assert.equal(parsed['进水水质::COD'].value,'0');assert.equal(parsed['出水水质::COD'].value,'<0.02');assert.equal(parsed['水量控制::日进水量'].value,'-1');assert.equal(parsed['进水水质::COD'].source,'IMPORT')})
test('导入身份、单位、口径、重复和异常原因严格检查',()=>{const rows=table.entryTable(metrics,cells,context);for(const patch of [{'项目ID':'site-B'},{'日期':'2026-09-06'},{'单位':'g/L'},{'填报口径':'瞬时值'},{'状态':'NA','说明':''},{'实际值':'=1+2'}])assert.throws(()=>table.parseEntryTable([{...rows[0],...patch}],metrics,cells,context));assert.throws(()=>table.parseEntryTable([rows[0],rows[0]],metrics,cells,context),/重复/)})
test('部分导入失败不改动当前草稿；旧模板无口径列仍可读取',()=>{const before=JSON.stringify(cells),rows=table.entryTable(metrics,cells,context);assert.throws(()=>table.parseEntryTable([rows[0],{...rows[1],'项目ID':'other'}],metrics,cells,context));assert.equal(JSON.stringify(cells),before);const legacy={...rows[0]};delete legacy['填报口径'];assert.doesNotThrow(()=>table.parseEntryTable([legacy],metrics,cells,context))})
console.log(JSON.stringify({result:'PASS',cases,formulaScope:'调用真实引擎、持久化与表格适配层；未复制实现逻辑'}))
